### ISSUE TITLE
Investigate IPython Notebooks and possible use as ELN

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#10085]
This issue was originally [TRAC 9242](http://trac.mantidproject.org/mantid/ticket/9242)

This ticket is blocked by : 
 - [X] [TRAC10502](http://trac.mantidproject.org/mantid/ticket/10502)
 - [X] [TRAC10826](http://trac.mantidproject.org/mantid/ticket/10826)

http://ipython.org/ipython-doc/stable/interactive/public_server.html

Questions:
1. Given a collection of ELNs, are/can they be searchable?
1. Can graphs be interactive, zoomable?
1. Can we get input to the notebook from instrument control, etc

 - - - - 
Keywords: SSC, 2015, All

**Comment by matthew-d-jones** [comment]
Added document to Mantid documents repository https://github.com/mantidproject/documents/blob/master/Design/IPythonAsELNs.md

**Comment by stuartcampbell** [comment]
I think @ricleal @wdzhou @JeanBilheux (as they have just come back from SciPy) might have some useful comments to add to the document.

**Comment by ricleal** [comment]
From SciPy 2015, I had the impression that mpld3 is dead... For interactive plotting within Notebooks, both Bokeh and IPython Widgets + Matplotlib appear to be the most active projects.
Any issues using matplotlib + IPython Widgets with Mantid?

**Comment by matthew-d-jones** [comment]
I suggested mpld3 over Bokeh as it is lighter and only requires normal matplotlib syntax. Having looked at mpld3's github it does look like there is not much going on in terms of development though.

The "IPython Widgets + matplotlib" option escaped my consideration. It would be great if you could add to the document if you know something about it. Otherwise I will take a look at it at some point.

**Comment by ricleal** [comment]
@matthew-d-jones I think it's better if you analyse the widgets by yourself since you reviewed the other options...

You can have a look at the tests I have here:
https://github.com/ricleal/PythonCode/tree/master/src/Widgets
Start with sin1 and sin2. You need to run this locally on your PC. Neither Github nor nbviewer show the widgets.

For more examples see: https://github.com/ipython/ipython/tree/master/examples/Interactive%20Widgets
Specially the ```Widgets*.ipynb```.

Let me know if you have any questions!

**Comment by matthew-d-jones** [comment]
@ricleal ok, thanks.

**Comment by matthew-d-jones** [comment]
I have updated
https://github.com/mantidproject/documents/blob/master/Design/IPythonAsELNs.md
with comments on using the "nbagg" matplotlib backend for zoom and pan controls. Also to state that ipython widgets can be used to add more powerful interactive features. These two tools are already included in Mantid's python environment and I suspect are sufficient.

**Comment by NickDraper** [comment]
Close the umbrella ticket the final item is tracked by #13699
