### ISSUE TITLE
Improve Single Crystal user experience

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#10144]
This issue was originally [TRAC 9301](http://trac.mantidproject.org/mantid/ticket/9301)

Discuss with users and get a list of definite requirements

---

Keywords: SSC,2014,All,SX

**Comment by samueljackson92** [comment]
Pascal mentioned he wanted some improvements to make the integrate ellipsoid algorithm follow a workflow similar to a two pass system used by programs from the ILL.

**Comment by samueljackson92** [comment]
Observed Pascal and found out more about his issues. There are several things to improve:
 - FindUBUsingLatticeParameters often returns the incorrect result for them in unit cells with high symmetry. The cause of this should be investigated before deciding on a direction.
 - Proposed new tool for instrument view. He would like a way to select two peaks and compute the angle and d-spacing between them. This would help with diagnostics in cases where automated peak finding fails.
 - A "SuperWISH" instrument definition for misaligned crystals. Basically they want to see predicted peaks that fall off of the instrument definition. The ability to zoom out to see peaks outside of detectors would also be useful.

**Comment by OwenArnold** [comment]
The graphical tool is obviously lacking, but @samueljackson92. @AndreiSavici and I added the angle calculation as a feature to (V3D quite a while back) I just thought I'd mention that in case it helped.

**Comment by AndreiSavici** [comment]
@samueljackson92 Just some clarification for point 1. Are the two peaks at the same goniometer angle? Not that it matters too much. You create the two corresponding peaks in `Q_sample` frame (you need to have the goniometer set on the workspace BEFORE you select peaks). Then you calculate the angle between the two Q_sample V3Ds.  If the two peaks belong to the same run (same goniometer) you can work with `Q_lab` instead. I would prefer `Q_sample` since it's more general.
What does calculating d-spacing `between` peaks mean? I can calculate d-spacing for each of the peaks.

**Comment by samueljackson92** [comment]
@AndreiSavici  1. The two peaks have the same goniometer angle. 2. My mistake, d-spacing for each.

**Comment by samueljackson92** [comment]
Further sub issues for this:
 - #17800 
 - #18043 
 - #18120 
 - #18240
