### ISSUE TITLE
Check docs of algorithms LoadFullprofResolution and ModifyDetectorDotDatFile

### ISSUE THREAD

**Issue by mantid-roman** [mantidproject/mantid#10584]
This issue was originally [TRAC 9742](http://trac.mantidproject.org/mantid/ticket/9742)

LoadFullprofResolution has broken links to algorithms.
ModifyDetectorDotDatFile has some wrong formatting.

**Comment by KarlPalmen** [comment]
All the links to other algorithms are correct in the documentation of these two algorithms, but some of the pages LoadFullProfResoltution links to have incorrect links to algorithms or concepts, probably because these documents remain in the wiki and link to algorithm or concept documents no longer there.

**Comment by KarlPalmen** [comment]
In ModifyDetectorDotDatFile RST file, the format of the file contents can be improved, if written in the same manner as the file contents in LoadAscii-v2 RST file.

**Comment by KarlPalmen** [comment]
I've improved the file contents format in the ModifyDetectorDotDatFile RST file and have fixed links in two documents linked by LoadFullProfResolution.
