### ISSUE TITLE
Interface with GSAS-II from Engg GUI for EnginX analysis

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/mantid#10630]
This issue was originally [TRAC 9788](http://trac.mantidproject.org/mantid/ticket/9788)

This ticket is blocks :  [TRAC8368](http://trac.mantidproject.org/mantid/ticket/8368)

From discussion with Saurabh Kabra.

Now http://trac.mantidproject.org/mantid/ticket/8760 has been done the next bigger task is to provide EnginX Python scripts that make external calls to GSAS, replicating existing typcial GSAS analysis on EnginX.

Note the main output of http://trac.mantidproject.org/mantid/ticket/8760 are two parameters Difc and Zero, which can be feed into GSAS input file. In addition from Mantid GSAS *.gss can be generated, and where necessary *.prm. Also, EnginX has a collection of GSAS phaseinformation (*.exp) files and GSAS sequence command files. The script will takes such inputs and returned a GSAS output that can be viewed with GSAS GUI.

Currently EnginX make calls to GSAS from OpenGenie scripts. Replicate these to python scripts that makes calls to GSAS. 

For this ticket assume that GSAS is pre-installed on the computer. If the script detect that this is not the case then the user should be pointed at a web-site explaning how to install GSAS so that the script can be used.

These scripts may be located in https://github.com/mantidproject/mantid/tree/master/Code/Mantid/scripts/Engineering or some subfolder of https://github.com/mantidproject/scriptrepository

**Comment by FedeMPouzols** [comment]
Updating the name. The objectives have changed since then.

**Comment by FedeMPouzols** [comment]
This work should be the basis for the new multi peak fitting section in the Engg GUI: #15552.

**Comment by FedeMPouzols** [comment]
Note that an updated version of this ticket has been implemented in #15890.
The OpenGenie scripts were not used because GSAS-II works quite different from what was assumed when this ticket was written.
For the phase information of the usual Engin-X materials we are now using CIF files. .exp files (the ones from GSAS-I I guess) are not used. 
The new algorithm does Pawley and Rietveld refinement in addition to fitting of individual peaks. It produces refine lattice parameters (the a, b, c, alpha, beta, gamma + volume). It saves GSAS-II project files (.gpx).
