### ISSUE TITLE
Crop workspace limits

### ISSUE THREAD

**Issue by AndreiSavici** [mantidproject/mantid#10887]
This issue was originally [TRAC 10045](http://trac.mantidproject.org/mantid/ticket/10045)

When using CropWorkspace on an event workspace, the output workspace should have the limits given by the XMin and XMax, instead of the original values

**Comment by FedeMPouzols** [comment]
@NickDraper: we saw this one which could also be a good "anyone" ticket.

**Comment by DimitarTasev** [comment]
@AndreiSavici @FedeMPouzols @NickDraper I tried using the CropWorkspace Algorithm, and the new workspace was within the XMin/XMax values. Also I believe the source code addresses this [here](https://github.com/mantidproject/mantid/blob/master/Framework/Algorithms/src/CropWorkspace.cpp#L66).

![screenshot_1](https://cloud.githubusercontent.com/assets/9135965/16915056/8b508338-4ced-11e6-8023-be4caa328e8e.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/9135965/16915030/57a29684-4ced-11e6-8577-f464a9f7bce2.png)

Unless the issue is addressing a different problem, I believe this one has been fixed at some point. If it is a different problem, could you please provide some information as to where I should look?

**Comment by AndreiSavici** [comment]
I agree that is fixed. Mark it as closed
