### ISSUE TITLE
BinMD does not accept MD histo workspace any more

### ISSUE THREAD

**Issue by abuts** [mantidproject/mantid#10898]
This issue was originally [TRAC 10056](http://trac.mantidproject.org/mantid/ticket/10056)

LoadMD the workspace FeSlice2bug.nxs  at 
ftp://ftp.nd.rl.ac.uk/scratch/abuts/Ticket_10056
and try to bin it

BinMD does not accept it (any more?). 

Accordingly, sliceViewer can not rebin it to a line.

**Comment by matthew-d-jones** [comment]
Due to changes to the parent workspace invalidating this kind of operation, we no longer retain a link between an MDHistoWorkspace and the MDEventWorkspace from which it was produced. The complication of Q transformation between the two workspaces is another reason.
Rebining an MDHistoWorkspace is therefore not possible, one would instead create a new MDHistoWorkspace from the original MDEventWorkspace using BinMD.

**Comment by abuts** [comment]
Hmm, 
How in this case one could observe Histo workspace in sliceviewer and be able to make 1D cuts?
I believe, this option is high on the request list from VATS and removing it violates all logic of using sliceviewer.  Similarly, Histo workspace is currently the only way to make e.g. Q-dE(Q.x-> fourth coordinate)  view of MD workspace in Paraview. Has it been fixed?

**Comment by matthew-d-jones** [comment]
@abuts 
For 1D plots we could use `MDHW::getLinePlot` which returns the value of the bin a point is in, for linearly spaced points along a line. This is not the same as integrating events within a certain radius of the line though, which I assume would be the desired behaviour. 
Is there a reason one can not look directly at the original MDEventWorkspace? Or is this after the workspace has been manipulated in some way which can only be done with HistoWS?

**Comment by abuts** [comment]
Very often a workspace has been manipulated. I am trying to assure Mantid has Horace functionality and there people used to deploy both options in a way they found convenient. Would getLinePlot work for tilted lines?
The ticket has been actually formulated while trying to investigate a histo-workspace using sliceviewer. 
It was generating errors on trying to produce 1D plots (do not remember which one -- seems even not tilted). If this fixed, then probably we may consider issue solved for the time being, though another case would be the Paraview, where you currently may need to rebin MD workspace to get Q-dE view. Then you may want to investigate the image in details but as nobody currently uses this, this is less important.

**Comment by NickDraper** [comment]
@OwenArnold Owen, you might want to step in on this conversation

**Comment by abuts** [comment]
I tried to view 1D slices out of 2D histo workspace in sliecviewer and though it does not crash as before, the behaviour is confusing. It plots something, but generates error messages on not being able to rebin. What does it plot then? Does it have any relation to reality? This is clear laps in functionality, which should be fixed. Not sure within this ticket or something else.

**Comment by matthew-d-jones** [comment]
@abuts Sorry, my original comment is incorrect, I misunderstood a conversation I had with Owen. After taking a look in the code, this is the situation:

The workspace loaded from FeSlice2bug.nxs is an MDHistoWorkspace, it cannot possibly be rebinned because the original MDEventWorkspace is not present and so BinMD correctly throws an error.

The Line Viewer uses IntegrateMDHistoWorkspace if the requested line is dimension aligned and BinMD otherwise. Again, this will fail if the original MDEventWorkspace is not present.
In the case that BinMD fails what will be plotted is the output of `getLinePlot` which is a set a points along the line plotted against the bin value at their position. The fact that rebinning failed and the reason for it is displayed in the log and clearly indicated in the Line Viewer in the title of the plot.

This all seems to me to be both sensible and working correctly. Does this leave you with any concerns? Perhaps the error message could be clearer?

**Comment by abuts** [comment]
yes -- though the minor one. But every user would be very confused trying to look at the plot. 

When you try to plot line on sliceviewer, the line plot has huge error message on top of it, telling that "this is error, look at the log" what user should assume?
Most have no idea and do not usually want to know what is behind the scene. 

After your detailed explanation I understand what is going on and what is there, but you would not explain it to every user. 

The cut width controls should be disabled for Histo workspaces and no error message be displayed over the plot.

**Comment by matthew-d-jones** [comment]
In the case that BinMD is successful the values from the width controls are used, they are only unused in the case that BinMD fails. We could disable them when BinMD fails though.

I think that it is important that the error is visible to the user, they need to know that the plot they are looking at is not what they requested and also why, so that they know how to get what they wanted.

**Comment by abuts** [comment]
I did not understand what this error mean. A user will not either. They will come to us complaining and will not be use software they not trust. The width controls and width indicators should be just disabled for histo workspace. 
Then user will see what is going on.

**Comment by matthew-d-jones** [comment]
We cannot disable the width controls for histo workspaces because if there is original event data available then they are used. The only thing we could do is disable them in the particular case that BinMD fails.

The current error message is
```
Error in execution of algorithm BinMD:
Cannot rebin a workspace that is histogrammed and has no original workspace that is an MDEventWorkspace.
Reprocess the input so that it contains full MDEvents.
```
This doesn't seem too bad to me, can you suggest something clearer?

**Comment by abuts** [comment]
I certainly know how to disable width indicators on the sliceviewer. I never looked into the cut-out box on the image itself, but sure something can be done about it too. HistoWS and MDEvent workspace are different classes so I do not see a problem to identify what to do before performing operations on workspace. This would be ideal solution.   

Other solutions are much more cumbersome but certainly should not contain word "Error" in it.  I know how our users react to this message, especially plotted in bold and red.  I can not come with solution I really like, but something similar to:
"Zero-width plot along selected direction. Return to MDEvent workspace to utilize the cut width." would be much better.
