### ISSUE TITLE
SaveAscii spectra indexing

### ISSUE THREAD

**Issue by raquelalvarezbanos** [mantidproject/mantid#11364]
This issue was originally [TRAC 10522](http://trac.mantidproject.org/mantid/ticket/10522)

To reproduce:
- Load https://github.com/mantidproject/mantid/blob/master/Test/AutoTestData/GEM38370_Focussed_Legacy.nxs, dataset has 6 spectra ranging from 2 to 7
- Execute SaveAscii with SpectrumList property set to "6,7". An error message indicating an "Inconsistent spectra list" is issued.

Also:
- Load any dataset, for instance https://github.com/mantidproject/mantid/blob/master/Test/AutoTestData/HET15869.raw, with spectra ranging from 1 to 2584.
- Try saving the last spectrum with SaveAscii. The "Inconsistent spectra list" error message is issued.

Spectra ID should range from 1 to N instead of 0 to N-1.

**Comment by lottiegreenwood** [comment]
From testing it looks like the "Inconsistent spectra list" no longer appears when trying to save spectra n+1... but it also looks like no error message appears when you try to save a spectra number the dataset doesn't have - it just fails silently and doesn't produce a file. It still needs to be fixed to range from 1 to n instead of 0 to n-1
