### ISSUE TITLE
Interface to CASTEP

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#12077]
This issue was originally [TRAC 11238](http://trac.mantidproject.org/mantid/ticket/11238)

May be some crossover with http://trac.mantidproject.org/mantid/ticket/11237

This was basically described as a wrapper for running CASTEP, an algorithm (possibly with custom interface) that took in parameters to create a CASTEP input file, ran castep and ingested the results.

---

Keywords: SSC, 2015, All, model

**Comment by mducle** [comment]
Getting Mantid to run Castep is not really something that's easy and is only a peripheral part of what Mantid should be doing (which is data reduction / analysis rather than running simulations). Users wanting an interface to CASTEP should look at Materials Studio instead.

There is also a project ([Euphonic](https://github.com/pace-neutrons/euphonic)) which can import CASTEP (and other DFT) data and generate neutron spectra from this. An interface to this code will eventually be incorporated into Abins and hence into Mantid.
