### ISSUE TITLE
Output transmission workspace as pointworkspace

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/mantid#12107]
This issue was originally [TRAC 11268](http://trac.mantidproject.org/mantid/ticket/11268)

At the moment transmission workspace is returned as histogram workspace. With the new devide by bin-width default this courses confusion.

Change this so transmission workspace is outputted as pointworkspace.

Richard suggests the following code change to fix this:

See, isis_reduction_steps.py, around line 1420, where return fittedtransws as pointworkspace (using ConvertToPointData):

{
        CalculateTransmission(SampleRunWorkspace=trans_tmp_out, DirectRunWorkspace=direct_tmp_out,
                              OutputWorkspace=fittedtransws, IncidentBeamMonitor=pre_sample,
                              TransmissionMonitor=post_sample,
                              RebinParams=reducer.to_wavelen.get_rebin(),
                              OutputUnfittedData=True, **options) # options FitMethod, PolynomialOrder if present

        # Remove temporaries
        files2delete = [trans_tmp_out]

        if direct_tmp_out != trans_tmp_out:
            files2delete.append(direct_tmp_out)

        if sel_settings[FITMETHOD] in ['OFF', 'CLEAR']:
            result = unfittedtransws
            files2delete.append(fittedtransws)
        else:
****            result = fittedtransws  *****

        reducer.deleteWorkspaces(files2delete)

        return result
}

For reference python code to check if histogram or pointworkspace:

{
histogram = CreateSampleWorkspace()
print "Histogram: ",histogram.isDistribution()
print "Distribution: ", histogram.isHistogramData()

ConvertToDistribution(histogram)
print "Histogram: ",histogram.isDistribution()
print "Distribution: ", histogram.isHistogramData()

point = ConvertToPointData(InputWorkspace=histogram)
print "Histogram: ",point.isDistribution()
print "Distribution: ", point.isHistogramData()
}

**Comment by picatess** [comment]
The issue appears because of the ```Fit``` Algorithm which is used within ```CalculateTransmission```. Before the ```Fit``` algorithm the workspace is a distrubution and after is not any longer. 
There are several options to fix this:
1. Set the workspace back to be a distribution manually at the end of ```CalculateTransmission```
2.  Convert the workspace with ConvertToPointWorkspace at the end of the reduction as a post-proecess step. 

If the only aspect this affects is plotting then we should go for option 1 otherwise if it also matters for latter fitting then we should go for option 2. In fact, we should go for option 1 any way if this is the correct output type

**Comment by picatess** [comment]
The issue was closed by #13885
