### ISSUE TITLE
Mantid become sensitive to network conditions

### ISSUE THREAD

**Issue by abuts** [mantidproject/mantid#12425]
This issue was originally [TRAC 11587](http://trac.mantidproject.org/mantid/ticket/11587)

A problems were observed when ISIS network have problems. In particular, the archive did not work well. 

Mantid become irresponsible, random crashes were observed on Windows and RHEL7, (I've seen 2 on windows and 1 on RHEL7 during 30 min attempted work) when no crashes, user sometimes was waiting for almost a minute looking at dimmed Mantid window when Mantid was trying to find a file on network or load it from network folders. 

Pretty grim experience and users blame Manitd.

**Comment by gemmaguest** [comment]
Mantid can also be very slow to start if the archive is slow. It seems to get stuck for ages going through the [recent files list](https://github.com/mantidproject/mantid/blob/master/MantidPlot/src/ApplicationWindow.cpp#L13687).

**Comment by gemmaguest** [comment]
Following PR #23443, I'm still getting slow startup, but now in different places. If I have files in `datasearch.directories` then it's slow [here](https://github.com/mantidproject/mantid/blob/master/Framework/Kernel/src/ConfigService.cpp#L556). Otherwise, it's slow when creating a QFileDialog [here](https://github.com/mantidproject/mantid/blob/master/qt/widgets/common/src/WorkspacePresenter/WorkspaceTreeWidget.cpp#L62).

**Comment by gvardany** [comment]
We also observed problems when the data are on the network mount. In case of intermittent connection interruption, Mantid freezes and you have to kill the process. The most annoying is that it gets stuck in some undetermined state, so you can not start it again even after kill. The only cure is to restart the computer. Unfortunately this is hard to reproduce.

**Comment by martyngigg** [comment]
Now that #28760 is merged I'm going to close this and we can open more specific issues in the future such as #28822 when/if we find other problems.
