### ISSUE TITLE
Step axis option issue

### ISSUE THREAD

**Issue by DanNixon** [mantidproject/mantid#12480]
This issue was originally [TRAC 11642](http://trac.mantidproject.org/mantid/ticket/11642)

Generate and plot this workspace:
```
CreateSampleWorkspace(OutputWorkspace='ws', XMin=-2000, XMax=10000, BinWidth=10)
```

Now try to set the bottom axis step value, the value cannot be set and selecting Step will give the warning "Scale options are invalid!".

**Comment by LamarMoore** [comment]
Seems that the real issue here is the minimum allowable step size is not being displayed/forced. If I run the code above and set the step size to be something sufficiently large, then any invalid step size defaults to the last successful entry. If you set a step size of 3000 using the example above it works.

**Comment by NickDraper** [comment]
wontfix
