### ISSUE TITLE
Enhanced graphical visualisation including Azimuthal aversing in sliceviewer

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#12676]
sans_feature
This issue was originally [TRAC 11838](http://trac.mantidproject.org/mantid/ticket/11838)

Owen to talk to Steve King / Richard Heenan to understand requirements and then discuss with PM for resourcing.

---

Keywords: sansUI

**Comment by OwenArnold** [comment]
@NickDraper @picatess Now that Anton is working on SANS, he can go directly to representatives from that technique are a to get requirements. This issue does not contain enough information.

@picatess If this turns out not to be important archive the issue and close it. If it is important, I should be able to offer help with technical aspects.

**Comment by OwenArnold** [comment]
@picatess I'm afraid I have no information about this issue. I don't remember this ever being discussed.

**Comment by DavidFair** [comment]
There is no associated requirements / discussion with this issue so I'm going to close it as stale.
