### ISSUE TITLE
LoadNexusMonitors outputs varying number of child workspaces when loading multiperiod data

### ISSUE THREAD

**Issue by picatess** [mantidproject/mantid#13032]
The number of elements in a group workspace which gets loaded when LoadNexusMonitor is run, depends on whether the output workspace is set explicitly or not. This issue was seen with multi-period event data. Although this might be more general than that.

The following script should help to clarify the issue and reproduces the issue:

1. Get the nexus file: LARMOR00002798.nxs which can be found in the data archive May/June 2015)
2. Run the following script
```python
# Create GroupWorkspace which seems to contain itself
file_path= XXXXXXX # This is the file path to LARMOR00002798.nxs. You need to set it!
ws_group= LoadNexusMonitors(Filename=file_path)
print "Length of the GroupWorkspace is: %s , but we expected 4." %len(ws_group)
print "The individual sub-workspace names are:"
for element in ws_group:
    print "Workspace: %s"%element.name()

print '###################################'
# Create GroupWorkspace as expected
out_name = "group_ws_test"
LoadNexusMonitors(Filename="C:/Users/xsd05043/Documents/SANS/12583/Event/LARMOR00002798.nxs", OutputWorkspace=out_name)
ws_group_2 = mtd[out_name]
print "Length of the GroupWorkspace is: %s and we expected 4." %len(ws_group_2)
print "The individual sub-workspace names are:"
for element in ws_group_2:
    print "Workspace: %s"%element.name()
```

The output is 
```
---------------------------------------------------------------------------
Length of the GroupWorkspace is: 5 , but we expected 4.
The individual sub-workspace names are:
Workspace: ws_group
Workspace: _1
Workspace: _2
Workspace: _3
Workspace: _4
###################################
Length of the GroupWorkspace is: 4 and we expected 4.
The individual sub-workspace names are:
Workspace: _1
Workspace: _2
Workspace: _3
Workspace: _4
---------------------------------------------------------------------------
Tue 7. Jul 13:00:32 2015: Script execution finished.
---------------------------------------------------------------------------
```

**Comment by MikeHart85** [comment]
It looks like the issue was caused by LoadNexusMonitors creating additional output workspace properties for each workspace in the group, in addition to the group itself. 

In the ADS this wasn't really visible; the additional output workspaces replaced the ones inside the group rather than being added. This had the side effect of changing their names, but did produce the correct number of workspaces.

In the Python interface, however, this meant that `LoadNexusMonitors()` returned a tuple instead of a single group workspace. The tuple contained the group workspace as the first element (with all of its children inside it), followed by an additional element for each child workspace.

So the return value effectively looked something like this:
```python
tuple (
  ws_group (_1, _2, _3, _4),
  _1,
  _2,
  _3,
  _4
)
```

Since the expected return value was just a group workspace by itself, iterating over it or checking its length made it look like a group with 5 children.
