### ISSUE TITLE
Add start and end times to the list of log values

### ISSUE THREAD

**Issue by raquelalvarezbanos** [mantidproject/mantid#13195]
From James Lord:

> Another item to add to the shopping list for Muon Analysis: It would be good to be able to put run start and end times in the fitted Results Table, so we can plot something versus time in a kinetic experiment. At the moment the times aren't in the list of log values I can choose. I had to plot versus Run Number which is only acceptable if the beam current is steady and all runs are the same length.

> The times of runs are there in the Sample Logs dialog and accessible from Python.

> ALC versus time may be useful too.

**Comment by tom-perkins** [comment]
*ALC:* Times should be in seconds, with zero being the start time of the first run. End times should also be relative to the start time of the first run (not the end).

*Muon Analysis (results table):* Would be good to have two options: start/end time (as text) and start/end time (seconds since start of first run)
