### ISSUE TITLE
Python Export for StringContainsValidator

### ISSUE THREAD

**Issue by ElliotAOram** [mantidproject/mantid#13316]
The StringContainsValidator doesn't have a matching Python export. It would nice to implement this so that the validator can also be used in Python.

**Comment by KarlPalmen** [comment]
I find the name of this class misleading. This is because ``Contains`` has no object and is followed by a noun ``Validator``, which thus appears to be the object of ``Contains``. The real purpose is to ensure that a given string contains a given substring or set of substrings.  A better name would be ``StringContainsSubstringValidator`` or ``StringContainsSubstringsValidator``.

**Comment by KarlPalmen** [comment]
Another possible name would be ``StringContainmentValidator``.
