### ISSUE TITLE
NormaliseByCurrent issue

### ISSUE THREAD

**Issue by peterfpeterson** [mantidproject/mantid#13387]
The order of `NormaliseByCurrent` and `CompressEvents` should not matter. However, if the user runs `FilterBadPulses` then they get different answers.
```python
a=LoadEventNexus(Filename="PG3_4866", OutputWorkspace="a")
a=FilterBadPulses(InputWorkspace=a, OutputWorkspace=a, LowerCutoff=95.)
a=NormaliseByCurrent(InputWorkspace=a, OutputWorkspace=a)
a=CompressEvents(InputWorkspace=a, OutputWorkspace=a, Tolerance=.01)

b=LoadEventNexus(Filename="PG3_4866", OutputWorkspace="b")
b=FilterBadPulses(InputWorkspace=b, OutputWorkspace=b, LowerCutoff=95.)
b=CompressEvents(InputWorkspace=b, OutputWorkspace=b, Tolerance=.01)
b=NormaliseByCurrent(InputWorkspace=b, OutputWorkspace=b)

CheckWorkspacesMatch(a,b)
```
Shows that the workspaces do not match when they should.

**Comment by wdzhou** [comment]
The only difference between two output workspaces comes from the standard error.  And the relative difference of the standard errors between the two workspaces are very small, i.e., around 10^-10.  Thus it is very likely that the difference roots from the numerical error caused by different order of calling CompressEvents and NormaliseByCurrent.  

Algorithm FindPeaksBackground calculate peak background by using standard error.  Therefore the trivial change of standard error can affect the result of FindPeaksBackground, and thus that of StripVanadiumPeaks.
