### ISSUE TITLE
Tomo tools scripts: add capability to save intermediate steps

### ISSUE THREAD

**Issue by FedeMPouzols** [mantidproject/mantid#13468]
It should be possible to save all the stack slices after every pre-processing and reconstruction step, in addition to the obvious reconstructed slices. This includes steps like "ROI/crop", "cleaning/median filter/filter spots", "normalize", "sinograms", etc.

Then the gui should make it easy to configure this.

**Comment by DimitarTasev** [comment]
I feel this is more of a debugging issue, rather than a necessary implementation to have for production. 
In any case a flag has been added for the reconstruction scripts that allows to execute a debug run, `-d` or `--debug` that will save every intermediate step inside the `pre-processing` subfolder. This is covered in #18379
