### ISSUE TITLE
Create default normalization dropdown for VSI

### ISSUE THREAD

**Issue by AntonPiccardoSelg** [mantidproject/mantid#13601]
We want a normalization dropdown for the VSI. There the user can specify a default normalization.

This is merely an alias to the normalization selection field in each filter properties. However, since we aim to eventually hide most properties and the pipeline browser, it would be nice to sync this property to a more prominent location.

**Comment by OwenArnold** [comment]
* Layout doesn't seem right. Too much vertical padding.
![image](https://cloud.githubusercontent.com/assets/1109536/10306254/8a33b940-6c1d-11e5-8d48-66a83f5cd784.png)
* Items should be in group box.
* No need for word initial. I think this is misleading.
* VSI help [page](http://www.mantidproject.org/VatesSimpleInterface_v2) would need updating for all these changes.
* Auto == AutoSelect. We should dynamically put some text next to what Auto means (ask Owen for details)
* Normalization property doesn't seem to update when I change it on the new top level menu.
* Since the VSI and the SliceViewer need the same control for this, lets create one that can really be reused by both.

**Comment by AntonPiccardoSelg** [comment]
Some work had been done for the VSI, but we thought that this could/should be shared with the SliceViewer

**Comment by AntonPiccardoSelg** [comment]
The normalization can be specified in the pipeline browser. It is very unlikely that resources will be allocated towards this task in the future. Hence I am closing this issue
