### ISSUE TITLE
Status bar for downloading in ISIS catalog stays at 50%

### ISSUE THREAD

**Issue by picatess** [mantidproject/mantid#13635]
The download status bar remains at 50% when downloading multiple files. THe files seem to have been downloaded, but the status bar does not finish

**Comment by MikeHart85** [comment]
Could not reproduce this on Ubuntu... progress bar increments in 100% / [number of files] steps as the files are being downloaded and fills to 100% once all files are downloaded (although it does stay visible instead of disappearing because of the keep-alive algorithm still running in the background).

Could you check whether you can still produce this issue?
