### ISSUE TITLE
Fix for CompactMD

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#14032]
This algorithm has been introduced here #13508.

I think we should not abort when we process a workspace of zeros (see my comments against previous PR). If `max` ends up == `min` in any dimension, then the workspace must be filled with zeros and we should just refuse to compact it at all just clone and return the InputWorkspace, and raise a warning. 

Should be very easy to fix.

@picatess: Any thoughts?

**Comment by picatess** [comment]
* I agree that if one dimension contains zeros, then this means that the workspace is zero. You are right, we should probably do nothing in this case (except for cloning).
*  Regarding the performance test. We expect to see a jump, since the test was adapted to take longer. It was about 0.4s on my machine -- the 1.8s might be a bit much, so we can take this down.
