### ISSUE TITLE
Refl Gui Bug

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#14058]
Here's the bug as reported by Max
```
I'm afraid there is quite a sever bug in the Reflectometry table in Mantid 3.5.0: it doesn't stitch the data. I have tried it on several PCs. It seems to process the two angles correctly, but as the output from the stitching it only give the high angle.
```

This relates to the older GUI, not the new one.

Lets get this fixed ASAP.

**Comment by OwenArnold** [comment]
There are things wrong here. 
1) Here's the plotting output taken from running the first row from INTER_NR_test2.tbl
![screen shot 2015-10-20 at 17 19 53](https://cloud.githubusercontent.com/assets/1109536/10613828/df76fa5c-774e-11e5-818c-7ec26af1a477.png)
Notice that the stitched and high angle I(Q) plots vary only by scale. The stitched one should be much wider to incorporate the IvsQ output from the first run.

2) Also this is somehow wrong. We seem to have lost the column for the 2nd run title?
![screen shot 2015-10-20 at 17 16 21](https://cloud.githubusercontent.com/assets/1109536/10613831/e3c657a6-774e-11e5-99e5-acadf218f9b5.png)

**Comment by MattKing06** [comment]
```python
#Setting QMin and QMax from Data directly
Qmin = min(w1.readX(0))
Qmax = max(w2.readX(0))

#We then reset QMin and QMax based off columns
if len(self.tableMain.item(row, i * 5 + 3).text()) > 0:
    Qmin = float(self.tableMain.item(row, i + 3).text())
if len(self.tableMain.item(row, i * 5 + 4).text()) > 0:
    Qmax = float(self.tableMain.item(row, i * 5 + 4).text())

#Qmin and Qmax are passed directly into the algorithm to stitch workspaces
wcomb = combineDataMulti(wksp, outputwksp, overlapLow, overlapHigh, Qmin, Qmax, -dqq, 1, keep=True)
```

I found that setting QMin and QMax based off the qmin and qmax columns can cause this bug to occur because we can change which columns we wish to display. For example, if we have all of the columns possible present, then Qmin's value (based off column position) will actually be the value found in the QMin value for the second run, not the QMin value of the first run.

Unless this cannot be corrected for good reason, I can't see why the values would be set from the columns instead of the actual data itself. However if it cannot be changed, then perhaps a better method of extracting the correct QMin and QMax should be implemented.
