### ISSUE TITLE
DataProcessingAlgorithm fetching from AnalysisDataService

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#14099]
ReflectometryReductionOneAuto should not have to go to the ADS to get workspaces. See for example [here](https://github.com/mantidproject/mantid/blob/master/Framework/Algorithms/src/ReflectometryReductionOneAuto.cpp#L516) Workspaces should be extracted directly from the properties. We should not use the ADS for indirection.

**Comment by OwenArnold** [comment]
@raquelalvarezbanos Ok. When you get to it ask me.

**Comment by MattKing06** [comment]
This has not been possible due to known issues between the ADS and WorkspaceGroups. Unfortunately we cannot access properties of child algorithms when they are workspace groups as this has not been exposed to `Algorithm` yet.

The only places that contained code accessing the ADS where `processGroups` and `checkGroups` both of which will only handle groups. So I believe, for now, this will not be achievable and the code should remain as it is.

**Comment by raquelalvarezbanos** [comment]
I've seen this [here](https://github.com/mantidproject/mantid/blob/master/Framework/Algorithms/src/PlotAsymmetryByLogValue.cpp#L558-L559) too, where we had to use `ScopedWorkspaces` to deal with groups.

**Comment by OwenArnold** [comment]
This is a problem, but can't be fixed until we deal with the core nature of the entanglement of the processing in mantid with the ADS. This is a problem which will eventually resurface until we fix those underlying problems.
