### ISSUE TITLE
EnggDiffractionGUI::Mantid crashes on valid and invalid run-num when Rebinning

### ISSUE THREAD

**Issue by shahrozahmed1** [mantidproject/mantid#14886]
`Interfaces/Engineering Diffraction/Pre-processing`
When Run number for Pre-processing tab is accessed by browse button, the run number seems to be accepts and the `Rebin` carries out how it should. However when a valid or an invalid run number is given, Mantid seems to be crashes. Being able to provide a run-number for Pre-processing could be rather useful for the next release.

**Comment by FedeMPouzols** [comment]
Aha, good catch. There should be a unit test case for this now that there are different ways of getting the run-number / file-name. I think the problem can be when calling `EnggDiffractionPresenter::loadToPreproc()` which re-throws the file not found and similar exceptions. These exceptions are not being caught [here](https://github.com/mantidproject/mantid/blob/master/MantidQt/CustomInterfaces/src/EnggDiffraction/EnggDiffractionPresenter.cpp#L1820) and [here](https://github.com/mantidproject/mantid/blob/master/MantidQt/CustomInterfaces/src/EnggDiffraction/EnggDiffractionPresenter.cpp#L1820). It looks to me as if `loadToPreproc()` should not re-throw. There are already informative error messages. And after calling `loadToPreproc()` if the workspace is null the code is printing an error message but it should probably return from the functions as well (methods `doRebinningtime()` and `doRebinningPulses()`. Otherwise you'll get a confusing cascade of error messages where anyway you already know that the steps after the failed `Load` are going to fail because the `Load` failed.
