### ISSUE TITLE
Adding a Peak in the SliceViewer can happen in regions of no-coverage

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#15162]
Issue reported by Pascal Manuel during Beta Testing for 3.6

**To Reproduce**
* Create a MDEventWorkspace in HKL space. The Topaz scripts under the VATES/Diffraction script section should help with this
* Ensure you have a PeaksWorkspace available.
* Open the SliceViewer and PeaksViewer mode with the PeaksWorkspace
* Using the "Add Peaks" button on the PeaksViewer add a peak to a non-zero region of the Q-space map. This should work.
* Now try adding a peak off the covered region. This causes an exception about detectors not being found. 

**Note on Fix**
This is probably down to the constructor of the Peak type, which tries to find a detector based on the HKL position. This will not be possible. It would be better to either catch this exception and not add the peak, or prevent the peak being added in the first place.

**Comment by picatess** [comment]
__Issue:__

```cpp
  boost::shared_ptr<const ReferenceFrame> refFrame =
      this->m_inst->getReferenceFrame();
  const V3D refBeamDir = refFrame->vecPointingAlongBeam();
  // Default for ki-kf has -q
  double qSign = 1.0;
  if (convention == "Crystallography")
    qSign = -1.0;
  const double qBeam = q.scalar_prod(refBeamDir) * qSign; 
```
produces a qBeam which is negative. This trips later on at

```cpp
  double one_over_wl = (norm_q * norm_q) / (2.0 * qBeam);
  double wl = (2.0 * M_PI) / one_over_wl;
  if (wl < 0.0) {
    std::ostringstream mess;
    mess << "Peak::setQLabFrame(): Wavelength found was negative (" << wl
         << " Ang)! This Q is not physical.";
    throw std::invalid_argument(mess.str());
  }
```

It is not immmedately obvious to mee that qBeam needs to be positive, but the check about this is quite clear. 

Solution:
As suggested by Owen we need to catch this error. Catching it from the algorithm my be prefereable since this would also deal with potential issue that the underlying instrument of the peaks workspace and the main workspace differ (due to wrong usage of the user).
