### ISSUE TITLE
Slice Viewer slices on bin boundaries rather than centres

### ISSUE THREAD

**Issue by matthew-d-jones** [mantidproject/mantid#15263]
This seems like an odd thing for it to do, and has caused problems, for example  #15260. When plotting MDHistoWorkspaces it causes the last slice (slider all the way to the right) to display no data (all NaN).

Part of the fix may be to change the slice range in `DimensionSliceWidget::setDimension()` to
```
double half_bin_width = m_dim->getBinWidth() * 0.5;
double min = m_dim->getMinimum() + half_bin_width;
double max = m_dim->getMaximum() - half_bin_width;
```
but this also affects the axis limits on the plot, which is undesirable.

**Comment by samueljackson92** [comment]
The fix applied in #15260 is causing an issue that showed up in #16860 where the integrated dimension shows the incorrect slice point because it is being forced to the minimum of the dimension. 

I suspect that the correct way to solve this is to fix this issue which is likely the root of the problem. An important confirmation of the fix would be to check that the problems in #15260 and #16860 are both solved together.
