### ISSUE TITLE
Extend SetUncertainties to allow user to set uncertainty to specified value

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/mantid#15326]
Extend SetUncertainties to allow user to set uncertainty to specified value.

http://docs.mantidproject.org/nightly/algorithms/SetUncertainties-v1.html

**Comment by DimitarTasev** [comment]
@Anders-Markvardsen Could you please clarify what you mean by "allow user to set uncertainty to specified value"? Would you like it changed to an empty string field, or to add another option which could be "Custom" which then would then take into account the information from a new field, which would otherwise be ignored?
