### ISSUE TITLE
Support for 2D detectors

### ISSUE THREAD

**Issue by raquelalvarezbanos** [mantidproject/mantid#15567]
At the moment Mantid does not contain an off-specular data reduction algorithm for reflectometry data, just a core q-conversion algorithm. 

This off-specular algorithm must:

* Work for 2D data reduction on linear detectors 
* Be easily extensible or work for 3D data reduction on 2D detectors
* Distinguish between different types of scattering (offspecular scattering and divergent beam modes)

One group with strong interest in getting this functionality is ISIS reflectometry. ESS is also interested and at SNS already has non-Mantid software for 3D data reduction of off-specular, which e.g. ISIS can learn from. 

This will become a key algorithm for reflectometry and it is worth spending extra time getting it to produce the right numbers and accommodating the different use cases.

Therefore it is recommended to first provide a technical specification (a workflow of the steps of this algorithm) of what this algorithm will do and have it agreed by reflectometry scientists at spallation sources (possibly also continue sources) before work on coding this algorithm is started. 

~~Estimated time 3m.~~ Possibly 1 year or more depending on scope (see comments below).

**Comment by raquelalvarezbanos** [comment]
This was closed by mistake. I am reopening it

**Comment by Anders-Markvardsen** [comment]
@gemmaguest I have changed the description and title of this issue to include comments I had from Max Skoda today and comments recently from Nina Steinke

**Comment by gemmaguest** [comment]
We need to have a detailed discussion with scientists to set out the requirements for this work. From initial discussions the work may include the following:
- 2D detectors
- Non-rectangular pixels
- Detector grouping
- Mask files
- Graphical way to define an area of interest (via a new tab on the GUI)
- Define a background area of interest
- Mask Q regions in time and/or space.
- Conversion to Q

Note that they currently expect to get 2D detectors some time from around Sept 2017 to Mar 2018.

Because of the broad and vague scope at the moment we have put an initial estimate of 1 to 2 years.

**Comment by gemmaguest** [comment]
Closing because this is now covered by its child issue #26481
