### ISSUE TITLE
Fix and Speed up project saving

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#15602]
Fix and Speed up project saving
- Save project as Python script (all graphs, viewers to expose python)
- Performance options?
- Partial Save functionality (select graphs / workspaces then only save what is needed)
- Express Save - Only save History from a workspace since it was last loaded, then rerun on Load Project, then regenerate graphs
- Complete Save (as currently)

sub tickets
- [x] #3383
- [x] #16672
- [x] #16719 
- [x] #16768
- [x] #16960
- [x] #16961
- [x] #16962
- [x] #16963
- [x] #16964
- [x] #16965
- [x] #17060 
- [x] #17228
- [ ] #17445
- [x] #17969

**Comment by NickDraper** [comment]
Specific notes from unscripted testing:

1D plot: quite good, retained zooming errors and text lables.
Waterfall plot: retaind appearance, but lost water fall plot option boxes
2D plot: lost arrows and lines (2D would probably too as well), Lost axis scaling and colour bar log and scaling
qtiplot table: good
3D plot basic recreation ok

**Comment by samueljackson92** [comment]
Some more notes on this:
 - Looks like most of the code for this is in the god-like ApplicationWindow. It would be nice to pull it out of there instead of just adding to that class.
 - There appears to be a single exposed method from the ApplicationWindow class (```saveProjectAs()```) which causes mantid to crash if you give it the tilde on OSX, i.e. ```saveProjectAs("~/test.mantid")``` but appears to work otherwise.

**Comment by samueljackson92** [comment]
I'm still currently working on #16719. I've managed to get wrangle Mantid so that we can actually test loading and saving automatically. This afternoon I got serious with unscripted testing and manually ran though a whole bunch of scenarios. I've compiled a list of tests below and noted what does/doesn't work. I'm sure there's even more cases which have been missed, but we can add to it as they are found.

All of the below were carried out on Mac OSX 10.11.5 (El Capitan). 

| No. | Description                                                          | Pass/Fail | Notes                                                                                                                                                                                                                                                              | Tickets |
|-----|----------------------------------------------------------------------|-----------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------|
| 1   | Save project with workspaces without plotting                        | Fail      | Project is saved, but the open workspace is not included in the project.                                                                                                                                                                                           |         |
| 2   | 1D plot with a single spectrum plotted                               | Pass      | Plot appears on original monitor (yet was positioned on second).                                                                                                                                                                                                   |         |
| 3   | 1D plot with multiple spectra plotted from the same workspace        | Pass      |                                                                                                                                                                                                                                                                    |         |
| 4   | 1D plot with axis labels changed                                     | Pass      |                                                                                                                                                                                                                                                                    |         |
| 5   | 1D plot with title changed                                           | Pass      |                                                                                                                                                                                                                                                                    |         |
| 6   | 1D plotting with two separate plots from two different workspaces    | Pass      |                                                                                                                                                                                                                                                                    |         |
| 7   | 1D plot with zooming applied.                                        | Pass      |                                                                                                                                                                                                                                                                    |         |
| 8   | 1D plot with error bars                                              | Pass      |                                                                                                                                                                                                                                                                    |         |
| 9   | 1D plot with resized window                                          | Fail      | Plot appears back at the expanded size, but the bottom of the plot is cut off. It looks like the window is resized to be the maximum allowed by the screen, but the plot itself retains the saved size. The option “Rescale to show all” is a work around for now. |         |
| 10  | A single 1D plot with two spectra from different workspaces.         | Pass      |                                                                                                                                                                                                                                                                    |         |
| 11  | 1D plot with logarithmic axes                                        | Pass      |                                                                                                                                                                                                                                                                    |         |
| 12  | 1D plot with font formatting changed                                 | Pass      |                                                                                                                                                                                                                                                                    |         |
| 13  | 1D plot with plot colours changed                                    | Pass      |                                                                                                                                                                                                                                                                    |         |
| 14  | 1D plot with scaled axes                                             | Pass      |                                                                                                                                                                                                                                                                    |         |
| 15  | 1D plot with legend moved                                            | Pass      |                                                                                                                                                                                                                                                                    |         |
| 16  | 1D plot with label                                                   | Pass      |                                                                                                                                                                                                                                                                    |         |
| 17  | 1D plot with arrow                                                   | Fail      | Arrow disappears when reloaded                                                                                                                                                                                                                                     |         |
| 18  | 1D plot with timestamp                                               | Pass      |                                                                                                                                                                                                                                                                    |         |
| 19  | 1D plot hide axes                                                    | Pass      |                                                                                                                                                                                                                                                                    |         |
| 20  | Waterfall plot with 5 spectra                                        | Fail      | Plot and styling retained, but the options on the top of the plot are lost.                                                                                                                                                                                        |         |
| 21  | Waterfall plot with 5 spectra and fill, reverse, and offsets applied | Pass      |                                                                                                                                                                                                                                                                    |         |
| 22  | 2D basic plot                                                        | Pass      |                                                                                                                                                                                                                                                                    |         |
| 23  | 2D plot with log colour axis                                         | Fail      | Logarithmic colour axis is not retained when the plot is reloaded                                                                                                                                                                                                  |         |
| 24  | 2D plot with axis scaling applied                                    | Pass      |                                                                                                                                                                                                                                                                    |         |
| 25  | 2D plot with contour lines                                           | Pass      |                                                                                                                                                                                                                                                                    |         |
| 26  | 2D plot with custom colour map                                       | Fail      | Does not restore the custom colour map. Appears to use something other than the default colour map.                                                                                                                                                                |         |
| 27  | 2D plot hide axes                                                    | Pass      | If the colour bar is hidden it will reappear after being loaded. This could be a bug or a design choice.                                                                                                                                                           |         |
| 28  | 2D plot with label                                                   | Pass      |                                                                                                                                                                                                                                                                    |         |
| 29  | 2D plot with arrow                                                   | Fail      | Arrow is present, but is in wrong location                                                                                                                                                                                                                         |         |
| 30  | 2D plot with timestamp                                               | Pass      |                                                                                                                                                                                                                                                                    |         |
| 31  | 3D plot basic                                                        | Pass      |                                                                                                                                                                                                                                                                    |         |
| 32  | 3D plot w/wo frame                                                   | Pass      |                                                                                                                                                                                                                                                                    |         |
| 33  | 3D plot with different formatting                                    | Pass      |                                                                                                                                                                                                                                                                    |         |
| 34  | 3D plot with animation                                               | Fail      | Animation is not reapplied after loading                                                                                                                                                                                                                           |         |
| 35  | 3D plot with log axis                                                | Fail      | Log axis is not retained after load                                                                                                                                                                                                                                |         |
| 36  | 3D plot with axis formatting                                         | Pass      |                                                                                                                                                                                                                                                                    |         |
| 37  | 3D plot with legend                                                  | Pass      |                                                                                                                                                                                                                                                                    |         |
| 38  | QtiPlot table basic                                                  | Pass      |                                                                                                                                                                                                                                                                    |         |
| 39  | QtiPlot table with statistics from column                            | Pass      |                                                                                                                                                                                                                                                                    |         |
| 40  | QtiPlot table sort columns                                           | Pass      |                                                                                                                                                                                                                                                                    |         |
| 41  | QtiPlot table rename columns                                         | Pass      |                                                                                                                                                                                                                                                                    |         |
| 42  | QtiPlot table clear some values                                      | Pass      |                                                                                                                                                                                                                                                                    |         |
| 43  | QtiPlot table with plot of column                                    | Pass      |                                                                                                                                                                                                                                                                    |         |
| 44  | Matrix workspace view (single)                                       | Pass      | The X/Y/E tab being viewed is not currently retained, but this isn’t a huge issue.                                                                                                                                                                                 |         |
| 45  | Matrix workspace view (multiple)                                     | Pass      |                                                                                                                                                                                                                                                                    |         |
| 46  | Resized matrix workspace                                             | Pass      |                                                                                                                                                                                                                                                                    |         |
| 47  | Modify matrix workspace cell width                                   | Pass      |                                                                                                                                                                                                                                                                    |         |
| 48  | Script Window script contents are saved                              | Pass      | Modified scripts do not register as a modification of the project, but scripts are saved anyway. Output of script is lost, but this is not necessarily essential.                                                                                                  |         |
| 49  | Script Window with multiple scripts open                             | Pass      |                                                                                                                                                                                                                                                                    |         |

**Comment by NickDraper** [comment]
Enough of this is done to close the umbrella ticket for this release
