### ISSUE TITLE
Odd behaviour of bin width normalisation in plot window with over plot of histogram and point data

### ISSUE THREAD

**Issue by Jon-Taylor** [mantidproject/mantid#15635]
Over plotting histogram and point data gives odd behaviour when using the right click normalise to bin width

case 1. Plot the histogram data first then over plot with point data. Normalisation is available but does not cycle correctly. it modifies the wrong data set with the bin width

case 2. Plot distribution data first, then plot histogram data. No normalisation option available

**Comment by martyngigg** [comment]
@Jon-Taylor The following script gives me a histogram and a point workspace:
```python
histogram = CreateSampleWorkspace(Function='Powder Diffraction',XMax=2000,BinWidth=2)
point = ConvertToPointData(histogram)
```
Overlaying them gives me a warning "You are overlaying distribution and non-distribution data!" Cycling the normalization option then shows the `Y` scale shifting as expected. The point data set doesn't move as there is no bin width to use and the data points are just plotted as is.

Is the problem here really the definitions of point data vs distribution being confusing?
