### ISSUE TITLE
New algorithm for background subtraction

### ISSUE THREAD

**Issue by raquelalvarezbanos** [mantidproject/mantid#16456]
This needs to be discussed with scientists. We need a new algorithm and/or option to `ReflectometryReductionOneAuto` that processes background instructions for background subtraction. This is applicable to both linear detectors and 2D detectors.

We should also add a way to graphically select the background region to the ISIS Reflectometry GUI

**Comment by gemmaguest** [comment]
This will include:
- [ ] Instrument background
  - the offspec reduction scripts have a simple background correction
  - SNS also have this?
- [ ] Offspecular background
  - ILL working on this?
- [ ] Dark counts
  - Rob at ISIS working on this?
  - SANS also interested

**Comment by gemmaguest** [comment]
Notes on SNS reflectometry background subtraction:

- They use the average of the 3 pixels each side of the peak. If they were to start again, they would fit the whole curve rather than use the 3 points each side, which already have a big error. This could also work in 2D by fitting the surface.
- They do a second correction for the wide shoulder outside the slits. This depends on the flux. This is a tiny correction. It's not always obvious where the edges are - it's somewhat guesswork.
- Dark counts (electric noise) are even tinier. SANS do it but it's not significant for reflectometry.

**Comment by soininen** [comment]
At ILL we use [`CalcualtePolynomialBackground`](http://docs.mantidproject.org/nightly/algorithms/CalculatePolynomialBackground-v1.html) with 0, 1 or 2 degree polynomial to do the background subtraction. The workspace needs to be `Transpose`d before fitting the polynomials. This is all done in `ReflectometryILLPreprocess`. The users have the option to select the degree and a pixel range to exclude from the fit.

**Comment by gemmaguest** [comment]
I'm re-opening this because there are more types of background calculation we would like to add
