### ISSUE TITLE
Auto-Floating Windows on Mac

### ISSUE THREAD

**Issue by LamarMoore** [mantidproject/mantid#16790]
*This issue is based on feedback I received on the Mantid training course held at the MLZ in Munich June 30 - July 1.*

Mac users at the MLZ indicated that they kept losing the graph windows behind the main application window when plotting and performing fits. The only ways to solve this issue was to change the window to a docked window as hidden windows are not easily accessible. This does not occur on windows.

**Comment by samueljackson92** [comment]
This annoys me no end as well. I found that the simplest fix for this is to add Qt::Tool to the Qt::WindowFlags to our floating window class to achieve the expected behaviour. However, this causes floating windows to have a slightly thinner title bar (see screenshot). I can't seem to find a combination of flags/options that undo that effect. I'll have more of a hunt tomorrow.

![screen shot 2016-07-06 at 16 00 15](https://cloud.githubusercontent.com/assets/2487781/16622652/cce6bf60-4392-11e6-9cd2-e670b1b180d9.png)
