### ISSUE TITLE
Engg GUI fitting tab: refactor

### ISSUE THREAD

**Issue by FedeMPouzols** [mantidproject/mantid#17301]
Following on  #17276, the code needs refactoring before adding more functionality/fixes. This concerns:
- Names of variables and methods
- Documenting methods and parameters
- Structure of methods (simplify for example `EnggDiffFittingPresenter::browsedFile()`,
`EnggDiffFittingPresenter::updateFittingDirVec()`, and possibly `EnggDiffFittingPresenter::fittingRunNoChanged()`).

**Comment by DavidFair** [comment]
Making a checklist of refactoring locations to complete 
- [ ] `updateFittingDirVec`
- [ ] `browsedFile`
- [ ] `fittingRunNoChanged`

**Comment by DavidFair** [comment]
In `enableMultiRun` we currently call `findFilePathsFromBaseName` multiple times. 
This means we walk the directory for every file which can be very expensive.

@FedeMPouzols One possible solution is we could possibly look at getting `findFilePathsFromBaseName` to return a mapping of files onto their found full file paths. This means we could pass in a vector with `n` number files to find in a directory and get their paths in a single call instead of multiple calls?

**Comment by FedeMPouzols** [comment]
@DavidFair: that makes perfect sense. We'd scan the directory and produce the map just once at the beginning. I'd definitely put it in the list. Addressing all these issues may take some time and/or unveil other issues, so the list could be split into several GitHub issues/PRs.

**Comment by DavidFair** [comment]
Ok i'll make a list as I go and open them in one big batch.
New issue candidates:
- [ ] Return mapping from `findFilePathsFromBaseNames` of base names onto maps to avoid multiple calls
