### ISSUE TITLE
Engg: Calibrate fails if both banks specified 

### ISSUE THREAD

**Issue by DavidFair** [mantidproject/mantid#17377]
### Expected behavior
`EnggCalibrate` should produce the same output with both banks set using `Bank="Both: North, South"` and running it twice using `Bank:North` and `Bank:South`
### Actual behavior
`EnggCalibrate` fails with the following error:
```
RuntimeError: The number of histograms in the input data workspace (2513) is bigger than the number of spectra (rows) in the integration workspace (2500)
  at line 111 in 'D:/MantidInstall/plugins/python/algorithms\EnggVanadiumCorrections.py'
  caused by line 128 in 'D:/MantidInstall/plugins/python/algorithms\EnggVanadiumCorrections.py'
  at line 129 in 'D:/MantidInstall/plugins/python/algorithms\EnggFocus.py'
  caused by line 254 in 'D:/MantidInstall/scripts/Engineering\EnggUtils.py'
  at line 142 in 'D:/MantidInstall/plugins/python/algorithms\EnggCalibrate.py'
  caused by line 223 in 'D:/MantidInstall/plugins/python/algorithms\EnggCalibrate.py'
  at line 253 in 'New script'
  caused by line 40 in 'New script'
  caused by line 112 in 'New script'
  caused by line 881 in 'D:/MantidInstall/bin\mantid\simpleapi.py'
```

### Steps to reproduce the behavior
To ensure it is not `EnggVanadiumCorrections` failing below first run that independently with the following params:
Vanadium Workspace: `ENGINX00246043.nxs`
Input Workspace: `ENGINX00249918.nxs`
Vanadium Curves Ws: `van_curves_ws`
Vanadium Integral Ws: `van_integral_ws`

Next run `EnggCalibrate` with the following parameters:
Input Workspace:  `ENGINX00249918.nxs`
Van Integration Workspace = `van_integral_ws`
Van Curves Workspace = `van_curves_ws`
Bank = `Both: North, South`

This should fail - if the bank is changed to `North` and subsequently `South` it will run correctly

### Platforms affected
All

**Comment by FedeMPouzols** [comment]
Nice fix!
Note that the routine `getDetIDsForBank()` uses the ENGIN-X "grouping" file. For other instruments, say IMAT:
- They would need to define an equivalent grouping file.
- The routine should be generalized to be able to get the grouping file for the instrument of the workspace instead of assuming it is ENGINX.

Note also that this routine and `getWsIndicesForBank()` are fairly slow (you will notice it can take a while to get the IDs sorted out at the beginning of the calibration). It would be a good candidate for optimization/rationalization in the future.
