### ISSUE TITLE
Move monitor integration to `ReflectometryWorkflowBase`

### ISSUE THREAD

**Issue by raquelalvarezbanos** [mantidproject/mantid#17390]
In `CreateTransmissionWorkspace.cpp`, [line 168](https://github.com/mantidproject/mantid/blob/master/Framework/Algorithms/src/CreateTransmissionWorkspace.cpp#L168):

```
// Monitor integration ... can this happen inside the toLam routine?
```

I think the answer is yes. If so, monitor integration should be moved to `ReflectometryWorkflowBase::toLamMonitor()`

In fact, I think it should even be possible to move all the steps to convert from TOF to wavelength to `ReflectometryWorkflowBase::toLam()`, including the division of detectors by monitors.

**Comment by PranavBahuguna** [comment]
While it does seem possible to migrate monitor integration to `ReflectometryWorkflowBase::toLamMonitor()`, I noticed that in `ReflectometryWorkflowBase::toLam()`, the monitor integration code would not be carried out if `monitorIndex` or `backgroundMinMax` were not initialised, in which case `makeUnityWorkspace()` would be executed instead of `toLamMonitor()`. Does this matter?

In addition, I could avoid this problem by placing the monitor integration code in `toLam()` itself rather than `toLamMonitor()`.

**Comment by raquelalvarezbanos** [comment]
No longer valid, we now have a new version of `CreateTransmissionWorkspace`.
