### ISSUE TITLE
FilterEvents gui can have backwards time 

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#18551]
### Expected behavior
All of the sample logs to produce plots where time always progresses forwards.  
### Actual behavior
For some cases the line drawn in the plot window is go backwards in time (see image). 
![filter](https://cloud.githubusercontent.com/assets/25006392/22296470/233763b4-e312-11e6-9b2a-ea0ef8e679a7.png)

### Steps to reproduce the behavior
I have used 
[CNCS_7860_event.zip](https://github.com/mantidproject/mantid/files/730091/CNCS_7860_event.zip) and the sample log phase1. I have also extracted the raw data from the file and got the blue line in the figure. Clearly the time always increases and the times are smaller in the raw data. 
### Platforms affected
Windows 7.

**Comment by NickDraper** [comment]
I can't reproduce this with the same data and log file with 3.9.0
![image](https://cloud.githubusercontent.com/assets/1017173/22928788/20a680b4-f2b0-11e6-9b74-9c1077b28ccb.png)

even when changing the line type to line rather than horizontal steps
![image](https://cloud.githubusercontent.com/assets/1017173/22928753/f55b22d4-f2af-11e6-8c48-3bc9079a0156.png)

Is there anything else that needs to be done to reproduce this?

**Comment by AnthonyLim23** [comment]
I cant reproduce it either with V3.8
