### ISSUE TITLE
Ensure new GUI meets scientists' requirements so the old GUI can be removed

### ISSUE THREAD

**Issue by raquelalvarezbanos** [mantidproject/mantid#18674]
When scientists are happy with the new GUI, remove the old one.

The work required for the new GUI to satisfy scientists' requirements comprises:

- [x] Complete the priority fixes/additions detailed on #21167
- [x] Agree with scientists a date/release (vX) when the old GUI will be removed
- [x] Add a warning to the old GUI that it is deprecated and will be removed by said date #21103
- [ ] Remove the old GUI (vX)

**Comment by gemmaguest** [comment]
There were some minor fixes required for the new GUI which will go into release 3.11. Hopefully we will be able to remove the old GUI in the next release after this.

**Comment by gemmaguest** [comment]
Having spoken to Mario about SURF, I'm adding a dependency on #20088 because they currently still need to use the old interface if they need to specify different transmission runs for different angles (it is much slower to do this in the new GUI at the moment). However, they need to use the new interface if they have more than three angles.

Mario also pointed out that users may only be here once a year and may not have time to learn the new interface, so would prefer to keep the old interface around for some time.

**Comment by gemmaguest** [comment]
I'm marking the dependency on #21167 complete as of v3.12 as this is done bar a couple of minor niggles. I therefore think we're ready to add the deprecation warning in v3.13

**Comment by gemmaguest** [comment]
Max has confirmed that we can remove the old GUI
