### ISSUE TITLE
A failed algorithm can't be canceled

### ISSUE THREAD

**Issue by raquelalvarezbanos** [mantidproject/mantid#18820]
### Expected behavior

Mantid should be able to cancel an algorithm that failed and it shouldn't hang if you try to close MantidPlot.

### Actual behavior

A failed algorithm can not be canceled. Then, MantidPlot hangs if you try to close it.

### Steps to reproduce the behavior

- Load `POLREF14882.nxs` which is a multi-period workspace
- Open `ConvertUnits` from the algorithm dialog. Select `POLREF14882` and set `Target=MomentumTransfer` and `AlignBins=True`.
- Try to cancel the algorithm from `Details`.

### Platforms affected

All? This seems to work on release 3.8.

**Comment by gemmaguest** [comment]
This is not a regression in v3.9.0, as I had thought - I can reproduce similar behaviour in v3.8.0, although with a different test case (because `ConvertUnits` doesn't throw in v3.8.0):

```
inWS=Load(Filename=r'POLREF00014882.NXS')
IvsQ, IvsQ_unbinned, IvsLam = ReflectometryReductionOneAuto(InputWorkspace=inWS)
```

The problem happens using both the GUI or a script. Confirmed on Windows 7 and Ubuntu 16.04.

**Comment by gemmaguest** [comment]
The problem is that an `ErrorNotification` does not get sent for the parent algorithm. One is sent for the first child algorithm, but the child is not registered with the `AlgorithmMonitor`, so no notification is received (i.e. here: https://github.com/mantidproject/mantid/blob/master/MantidPlot/src/Mantid/AlgorithmMonitor.cpp#L103)

I think the solution is to catch the error and send an `ErrorNotification` for the parent algorithm here: https://github.com/mantidproject/mantid/blob/master/Framework/API/src/Algorithm.cpp#L531

I think this should be straightforward. I just need to check whether any other error handling needs to be done at this point.

**Comment by gemmaguest** [comment]
After talking to @martyngigg about this, we decided the best place for the `ErrorNotification` would be inside `doCallProcessGroups`, because this is where the `FinishedNotification` is: https://github.com/mantidproject/mantid/blob/master/Framework/API/src/Algorithm.cpp#L1194
