### ISSUE TITLE
Clarify documentation for LoadInstrument

### ISSUE THREAD

**Issue by DavidFair** [mantidproject/mantid#19071]
The `RewriteSpectraMap` option does within `LoadInstrument` is not very clear for example what happens if it is set to false. 
Update and clarify the documentation with the help of @DimitarTasev 

http://docs.mantidproject.org/nightly/algorithms/LoadInstrument-v1.html

**Comment by DavidFair** [comment]
Actually looking at the parameter description it describes the behaviour pretty well - I can't see any reason to change it. What do you think @DimitarTasev ?

**Comment by DimitarTasev** [comment]
@DavidFair We could clarify what happens if set to `unset` and `false`, as this makes me think why did it work when I set it to `false`, did it keep the current structure in the nexus file (likely), and assign the matching bank IDs from the IDF to the matching spectra numbers? What is the difference between `unset` and `false`? 

We could extend the documentation to clarify more about the functionality.
