### ISSUE TITLE
ISIS Reflectometry: Allow setting multiple transmission runs for specific angles

### ISSUE THREAD

**Issue by PranavBahuguna** [mantidproject/mantid#20088]
One of problems instrument scientists have with the current interface is that the `Transmission run(s)` setting in the `Settings` tab simply applies any specified transmission runs to all runs in the processing table. It lacks any capability to specify different transmission runs for runs with different specific angles, so they are forced to input these transmission runs in the table directly.

The `Transmission run(s)` setting needs to be changed to allow the user to input up to 2 transmission runs per angle. One possible way of doing this is to let the user input a map of angles to the transmission runs that can later be parsed, ideally in a table. For example:

| Angle | Transmission Run(s) |
|-|-|
| | 12345,12346|
| 0.5 | 22345,22346 |
| 2.3 | 32345,32346|

When we process the row, we should parse this input to apply any specified transmission runs to all runs with an angle that matches, within a certain tolerance (e.g. 100th of a degree). We should also allow a default to be specified without needing an angle lookup, e.g. by leaving the angle blank. We should only allow one default i.e. give a warning if a user enters more than one row with a blank angle.

If an angle is not specified in a row in the Runs tab, then the lookup will not be done (other than to use the default, if one was given). However, the angle will be found as part of the reduction algorithm and then populated in the table. This could possibly result in different results if you then re-run the processing, because the angle lookup will subsequently be done because it is now available in the table. To avoid confusion, we will initially disallow processing rows without an angle if per-angle settings are specified. This will not affect runs that are transferred from the Search box because they will have the angle populated. 

Ideally we should look up the angle from the log file and populate it before doing the lookup. This should be possible but is not straightforward, so needs some thought.

**Comment by gemmaguest** [comment]
Max's original suggestion was to do this as a table, which would probably be the most user-friendly way of inputting the data, although Pranav thought this may be difficult to implement. Max doesn't mind if we use an alternative input based on the existing single text box, however it needs to be easy for users to edit/read and easy for Mantid to parse. Users are familiar with python so perhaps something like a dictionary initialization syntax could be an option. We could also consider a multi-line text entry box, e.g.
```
0.7 : 12345, 12346
2.3 : 23456, 23457
```

Note that we usually have 2 angles, but there may be more (probably 4 at most).

**Comment by gemmaguest** [comment]
Note that angle lookup should match to about 100th of a degree, i.e. if the table has an angle of 0.7 but the run has an angle of 0.69, then this should match.

**Comment by gemmaguest** [comment]
I'm going to look at this next as part of #21167

**Comment by gemmaguest** [comment]
Max mentioned that there is also a requirement on Crisp to specify lambdaMin and lambdaMax on a per-angle basis. He suggested adding additional columns to the transmission runs table to essentially reproduce the table on the Runs tab so that all properties can be specified on a per-angle basis (note however that lambdaMin and lambdaMax can only be specified via the Options column on the Runs tab - there is no dedicated column).

Mario would actually prefer to keep the autofill functionality. @edwardb96 suggested that this could be done using a filter on the Runs tab and then autofilling the filtered rows. This could be a neater approach (we need to add a filter anyway). However, the angle may not be populated in the table initially when a run is typed in manually. Perhaps this angle could be populated after the run number is entered, or when a filter is performed, but this could be slow because it means loading the runs.

**Comment by martyngigg** [comment]
Closed after merging #21762 to release branch.
