### ISSUE TITLE
Enforce the associative property for ProductFunction

### ISSUE THREAD

**Issue by jmborr** [mantidproject/mantid#20250]
Given functions `f`, `g`, and `h`, enforce that the three expressions `(f * g) * h`,  `f * (g * h)`, and `f * g * h` result in the same `ProductFunction` object.

**Comment by jmborr** [comment]
@mantid-roman @KarlPalmen I have opened this issue to start addressing the issues that promted `castToCompositeFunction`

**Comment by KarlPalmen** [comment]
Issue #19010 currently enforces the associative of a pure product function (one without any composite functions as members that are not also pure product functions), by means ``castToCompositeFunction``.
This was needed because ``ProductFunction`` does not accesses any product function it contains as an IFunction rather than a Composite Function.

**Comment by jmborr** [comment]
this is being dealt with through the python API
