### ISSUE TITLE
Engineering diffraction

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#20836]
Gui freezes Mantid and give useless error dialog

![image](https://user-images.githubusercontent.com/1017173/31270077-c107a02e-aa7a-11e7-8afa-be356b26a2ad.png)

**Comment by AntonPiccardoSelg** [comment]
The dialog appears by design. 
The issue with freezing is related to the `MWRunFiles` widget [here](https://github.com/mantidproject/mantid/blob/master/qt/scientific_interfaces/EnggDiffraction/EnggDiffractionViewQtGUI.cpp#L136:L137) which then triggers the `MWRunFiles::findFile` method which then spends a lot of time in [here](https://github.com/mantidproject/mantid/blob/master/qt/widgets/common/src/MWRunFiles.cpp#L707).

It is not clear how we could improve this at the moment.

**Comment by NickDraper** [comment]
If you turn off searching the data archive the GUI starts instantly.

I'm looking at if you can turn off searching for the default files numbers when you first start up.
