### ISSUE TITLE
Write a system test for MSDFit when using the output from ELWIN with BASIS files

### ISSUE THREAD

**Issue by jmborr** [mantidproject/mantid#21296]
There is no system test to assess calculation of MSD values for BASIS-derived elastic intensities..

**Comment by SpencerHowells** [comment]
@jmborr Which version are you using? Brandon is doing a big re-write of the fitting interfaces issue #21123   harmonising the 4 fitting tabs. They will all use the same graphics methods. We also identified many bugs in 3.11 which will also be sorted out. MsdFit now requires the _eq file not _eq2 in order to fit the 3 models.

**Comment by jmborr** [comment]
@SpencerHowells   @brandonhewer  Ouch! I was using `_eq2`, as customary. I tried with `_eq` and I get reasonable fits :smile:.
The [documentation](http://docs.mantidproject.org/nightly/interfaces/Indirect%20Data%20Analysis.html#msd-fit) has not been updated because it reads that the input file in MSD tab is "A file that has been created using the Elwin tab with an x axis of Q^2".

**Comment by brandonhewer** [comment]
@jmborr @SpencerHowells I'll look into updating the documentation 😄
