### ISSUE TITLE
MaxEnt: return the number of MaxEnt iterations for each dataset

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/mantid#21444]
Make the alg return the correct number of maxent iterations when running the maxent alg with multiple input datasets.

When running the script:

[maxentTest.zip](https://github.com/mantidproject/mantid/files/1642342/maxentTest.zip)

it returns:

`Number of iterations dataset1: 11`
`Number of iterations dataset2: 7`
`Number of iterations dataset1: 9`
`Number of iterations dataset2: 9`

whereas it should return:

`Number of iterations dataset1: 11`
`Number of iterations dataset2: 7`
`Number of iterations dataset1: 11`
`Number of iterations dataset2: 7`

* fix this. This means 1) allow individual number of iterations to be extracted from the maxent output 2) ensure the right number of iterations are returned
* add the attached python code as a new Usage example
* ensure the documentation for how to get number of iterations is up to date

**Comment by AnthonyLim23** [comment]
can we talk about this in the new year? I don't understand what you are asking for.

**Comment by Anders-Markvardsen** [comment]
I will make a start on this one

**Comment by KarlPalmen** [comment]
@Anders-Markvardsen  I had a look at the workspaces using the script modified so that the workspaces created by the second P run were named differently (`...P2`), so I could examine all workspaces. I find that `evolAngleC` workspace not only has different length spectra to the `evolAngleP` and `evolAngleC` the values appear to be different. 

Do you want the first spectrum of `evolAngleC` to equal `evolAngleP` and the second spectrum of `evolAngleC` to equal `evolAngleP2`?

I'll examine the code to see how this could be ensured.

**Comment by KarlPalmen** [comment]
@Anders-Markvardsen  After lots of debugging and examining workspaces, I found out that the script combined the two workspaces incorrectly. The error values were in the wrong order. After correcting to 
```
CreateWorkspace(OutputWorkspace='wsCombined',DataX=X+X2+X+X2,DataY=YRe+YRe2+YIm+YIm2,DataE=E+E2+E+E2,NSpec=4)
```
I get the results:
```
Number of iterations dataset1: 11
Number of iterations dataset2: 7
Number of iterations dataset1: 11
Number of iterations dataset2: 11
```
The dataset2 of the combined workspace was padded out with zeroes. All behaviour seems to the OK, except that the values of dataset2 in the combined workspace are different for the 7 non-zero values and start with the same value as for the dataset1. These datasets are for the angle, the Chi values are the same for separate and combined workspaces, except for the zero padding.

**Comment by KarlPalmen** [comment]
@Anders-Markvardsen  A further check of the angles show they are identical for the separate and combined workspaces, except for the zero padding.

I no longer see an issue here, expect possibly removing the zero padding.

**Comment by KarlPalmen** [comment]
To ensure error-free combining of workspaces, one could modify the algorithm `AppendSpectra` to deal with complex valued spectra as in this issue. In the current form, it won't do this, because we use `(R1, R2, ..., I1,  I2, ...)` ordering rather than `(R1, I1, R2, I2,...)` ordering. http://docs.mantidproject.org/nightly/algorithms/AppendSpectra-v1.html

**Comment by KarlPalmen** [comment]
I checked the documentation at http://docs.mantidproject.org/nightly/algorithms/MaxEnt-v1.html and find that its descriptions of the number of bins in `evolAngle` and `evolChi` are not correct. It is the maximum number of iterations DONE (11) rather than the maximum number of iterations ALLOWED (20,000).

**Comment by Anders-Markvardsen** [comment]
Many thanks for this investigations.

In terms of this issue I would like the output to be:

```
Number of iterations dataset1: 11
Number of iterations dataset2: 7
Number of iterations dataset1: 11
Number of iterations dataset2: 7
```

I am not in tomorrow. @AnthonyLim23 will also be able to help with question of this issue.

I agree that the document is out-of-date for evolAngle and evalChi. Please update these thanks

**Comment by AnthonyLim23** [comment]
Here is the code I changed to trim the zeros (but kept a ws with all spectra the same length) https://github.com/mantidproject/mantid/pull/21435/files

**Comment by KarlPalmen** [comment]
I found that @AnthonyLim23 attempted to limit the spectra of the `evolAngle` and `evolChi` to the actual number of iterations done rather then the maximum number of iterations done, so producing a ragged workspace, but this fell foul of poor support of ragged workspaces then. The code for this is at  https://github.com/mantidproject/mantid/pull/21435/files .

**Comment by KarlPalmen** [comment]
Actually the code in the link is the actual code now. Ragged workspace was not attempted.

**Comment by Anders-Markvardsen** [comment]
@KarlPalmen let e.g. @AnthonyLim23 or me know when you have a PR reading for testing for this issue
