### ISSUE TITLE
Propagation of uncertainties wrong in Rebin2D

### ISSUE THREAD

**Issue by SimonHeybrock** [mantidproject/mantid#21688]
Based on discussions with @mducle and @Jon-Taylor during the developer meeting:

My understanding is that `Rebin` is handling uncertainties correctly, whereas `Rebin2D` is wrong. The argument can be made in several ways, for example:
- A shift of the bin edges by, e.g., half a bin width should keep the errors the same.
- A rebin to a finer or coarser bin width should keep the error on the mean fixed, e.g., when fitting a constant to a section of data.

The relevant code is in `FractionalRebinning.cpp`, e.g., https://github.com/mantidproject/mantid/blob/master/Framework/DataObjects/src/FractionalRebinning.cpp#L150. The multiplication with the weight should be done *after* squaring the error, which is what `Rebin` does.

The effect of this issue is a systematic *underestimation* of the errors.

**Comment by SimonHeybrock** [comment]
On second thought, I believe this is not a simple as stated above: If we consider a single result bin in isolation, then what `Rebin2D` does could actually be considered correct. Consider the following example, `|` denoting old bin boundaries, `I` denoting new bin boundaries:

```
spec 1 | I | I |
spec 2 | I | I |
spec 3 | I | I |
```

We are cutting the original bins in half, but since its value comes from a larger measurement area our knowledge of the uncertainty is actually better, so if we use the current way of computing uncertainties in `Rebin2D` (`\sigma_f^2 = (\sigma_1/2)^2 + (\sigma_2/2)^2`) our result is the same as the standard error of the mean of the input bins, `\sigma_f = \sigma / \sqrt{2}`.

I believe if all we wanted was this single result bin then this would probably be correct. However, we have to consider the more general case of multiple output bins (or other multiple use of the original data):

```
spec 1 | I | I | I |
spec 2 | I | I | I |
spec 3 | I | I | I |
```

Now we have two output bins, say `A` and `B`. If we compute their `\sigma_A` and `\sigma_B` as above, there will be a very strong cross correlation between them (something like `\sigma_AB = \sigma_2^2/2`?), because both use the value and error of input bin 2 to full extent. If Mantid would keep track of cross correlations we could probably do this (if all fits would take cross correlations into account, plots would be harder to interpret). Since we are not doing this, the "`Rebin`" way of doing things (basically interpreting the counts in each input bin split into sub-bins matching the output) seems more correct.

That being said, if all we do is extract a 1D curve from 2D data the `Rebin2D` way actually does not look wrong *provided that everyone / every user is aware that there is a non-zero correlation if this 1D curve is compared with any other data extracted from the same 2D data*.

**Comment by mducle** [comment]
For people unfamiliar with the issue, the background is here: 
[mantid_rebin_errors.pdf](https://github.com/mantidproject/mantid/files/1702768/mantid_rebin_errors.pdf)

**Comment by mducle** [comment]
@SimonHeybrock @Jon-Taylor 

Firstly, I've looked at a couple of other codes: 

1. [DAVE](https://www.ncnr.nist.gov/dave/downloads/dave_dev_src_2018-01-26.zip) does it the `Rebin` way [line 74-75 of drebin.pro]
2. [LAMP](http://ftp.ill.fr/pub/cs/lamp.tar.gz) does it the `Rebin2D` way [line 270 of reb.pro]

I've also gone around and pestered various people here. Most people (as expected) didn't have any idea and assumed that Mantid was "doing the right thing". When presented with the two methods most thought the `Rebin` way was more intuitive but could then be convinced that the `Rebin2D` way is statistically correct. 

There were a few people who very strongly felt that the `Rebin` way is _wrong_ and that Mantid should be using the `Rebin2D` way consistently. There does not seem to be very strong feelings the other way. People who felt strongly that we should use the `Rebin2D` method mostly come from the excitations group, which also uses `Rebin2D` (and associated `SofQW*` algorithms) extensively. There would be quite a strong push back if this routine was modified.

Now, the issue is that after rebinning the errors become correlated, as you noted. This means that subsequent operations on the rebinned data will probably treat the errors incorrectly (Mantid always uses the quadrature formula which is valid only for uncorrelated data, whereas the rebinned data, unless the new bin edges are aligned with the old, has some correlated bins). However, in some of the reduction scripts there are instances of a `Rebin` to align the bins followed by a `Minus` to subtract a background from a workspace. Whilst this operation is not strictly valid, I can't see any way of avoiding it in many cases... And using the `Rebin2D` way will probably lead to an underestimate of the errors, whilst using the `Rebin` way will overestimate the errors.

Anyway, maybe the best way forward is to use event mode data as much as possible and only histogram it right at the end (just before plotting!). However, the hardware here is geared almost entirely to histogram data collection and true event mode handling has been promised to us for many years without being delivered yet.

**Comment by SimonHeybrock** [comment]
In my understanding:
1. There is no "choice" regarding what `Rebin` does, it is **not a matter of opinion**. The error on the mean needs to be preserved and that uniquely determines the correct implementation.
2. As I discussed in my previous post, for `Rebin2D` we may have a choice. But the choice is not a matter of choicing a way of handling the errors. It is a matter of choosing a precise definition of what `Rebin2D` actually does (cutting a polygon from contiguous 2D data, vs. averaging all data points within a polygon).

I am not sure I understand your statement of `Rebin` overestimating the errors in a background subtraction.

**Comment by SimonHeybrock** [comment]
Regarding "strong push back if this routine was modified": If we can show convincingly that the current implementation is wrong, we fix it. People preferring smaller (but wrong) error bars on their data is not something we should take into account .

**Comment by mducle** [comment]
@SimonHeybrock Actually, I'm convinced (as is most of my group actually) that what `Rebin` does is **mathematically** wrong, and what `Rebin2D` does is right. I.e. we think that "preserving the error on the mean" is not valid - because we're not talking about averaging a set of events into a bin, but rather repartitioning a single bin (which is perhaps also a dubious operation). Since we think what `Rebin` is doing is wrong, we definitely don't want `Rebin2D` to be changed to doing the same (wrong) thing! This is why there will be resistance to changing it. Sorry if that was a bit blunt (!)

In any case, the difference between the two algorithms only happen when partitioning bins. E.g. if the bins edges of the rebinned workspace are aligned with the bin edges of the original, both give the same result because the fractional area will be unity:

```
ws = CreateWorkspace(range(10), [100]*10, [10]*10, VerticalAxisUnit='DeltaE', VerticalAxisValues=[0])
ws = ConvertToHistogram(ws)
wsr = Rebin(ws, '-0.5,2,9.5', False, False); wsr = wsr / 2
wsr2 = Rebin2D(ws, '-0.5,2,9.5', '-1,2,1'); wsr2 = wsr2 / 2
yy = wsr.readY(0)
ee = wsr.readE(0)
yy2= wsr2.readY(0)
ee2 = wsr2.readE(0)
print "Rebin          | Rebin2D"
for i in range(len(yy)):
    print "%3.0f +/- %5.3f  |  %3.0f  +/- %5.3f" % (yy[i], ee[i], yy2[i], ee2[i])
```

gives

```
Rebin          | Rebin2D
100 +/- 7.071  |  100  +/- 7.071
100 +/- 7.071  |  100  +/- 7.071
100 +/- 7.071  |  100  +/- 7.071
100 +/- 7.071  |  100  +/- 7.071
100 +/- 7.071  |  100  +/- 7.071
```

**Comment by mducle** [comment]
Regarding how to think about `Rebin2D` - I think it should be treated as cutting polygons from 2D bins - e.g. not as operating on a set of 1D spectrum. Thus the distinction of correlations in the vertical (between spectra) or horizontal (between neighbouring bins) is immaterial.

In any case, as soon as you partition a bin, you will always get correlations between the two new bins which contains part of the single original bins, and both `Rebin` and `Rebin2D` allow this. However, Mantid treats each operation of workspaces as applying to uncorrelated bins. Thus, _strictly_, the calculations of errors for any Mantid workspace operation after a rebin is wrong. The way that `Rebin` treats errors masks this by essentially doing a kind of interpolation, whereas if the errors are treated as in `Rebin2D` this will become more apparent (as the error bars shrink more and more).

However, in practical terms, we cannot forbid all operations on histogram workspaces after a rebin. Also in practical terms, I think in future if we keep as much processing in event-mode as possible then this problem will not arise.

**Comment by SimonHeybrock** [comment]
If you consider statistics part of mathematics, I do not understand how you can consider what `Rebin2D` is doing better than `Rebin`. Preserving the "error on the mean" is just the simplest example there is. You can make the same argument for fitting anything to you data, such as a gaussian to a peak. As far as I understand most users fit something to their data sooner or later.

Regarding "In any case, the difference between the two algorithms only happen when partitioning bins" --- true, but very frequently bins are not aligned. For example, if you `Rebin` after `ConvertUnits` the bins of the individual spectra often differ from each other so there cannot be alignment across all spectra.

For better illustration of the issue, here is an example where `Rebin2D` converts data that has a signal consistent with 0.0 into data that has a significant (sigma > 2) signal above zero:

```python
import numpy as np
from mantid.simpleapi import *

points = 100
mean = 0.0
sigma = 1.0
np.random.seed(0)
counts = np.random.normal(mean, sigma, points) + 0.1*sigma
errors = [1.0]*points
step = 1.0
binWidth = 1.0
binEdges = np.arange(points+1) * binWidth

ws = CreateWorkspace(DataX=binEdges, DataY=counts, DataE=errors, VerticalAxisUnit='DeltaE', VerticalAxisValues=[0])

offset = 0.5*binWidth
binning = '{},{},{}'.format(offset, binWidth,binEdges[-2]+offset)
wsRebin = Rebin(ws, binning, False, False);
wsRebin2D = Rebin2D(ws, binning, '-0.5,1,0.5', False, False);

Fit(Function='name=FlatBackground,A0=0.0', InputWorkspace='ws', Minimizer='Conjugate gradient (Fletcher-Reeves imp.)', CreateOutput=True)
Fit(Function='name=FlatBackground,A0=0.0', InputWorkspace='wsRebin', Minimizer='Conjugate gradient (Fletcher-Reeves imp.)', CreateOutput=True)
Fit(Function='name=FlatBackground,A0=0.0', InputWorkspace='wsRebin2D', Minimizer='Conjugate gradient (Fletcher-Reeves imp.)', CreateOutput=True)

fitted = mtd['ws_Parameters'].row(0)
print('Significance of non-zero background: {} sigma'.format(fitted['Value']/fitted['Error']))
fitted = mtd['wsRebin_Parameters'].row(0)
print('Significance of non-zero background after Rebin: {} sigma'.format(fitted['Value']/fitted['Error']))
fitted = mtd['wsRebin2D_Parameters'].row(0)
print('Significance of non-zero background after Rebin2D: {} sigma'.format(fitted['Value']/fitted['Error']))
```

Prints
```
Significance of non-zero background: 1.59808015534 sigma
Significance of non-zero background after Rebin: 1.48676866498 sigma
Significance of non-zero background after Rebin2D: 2.1025585511 sigma
```

**Comment by mantid-roman** [comment]
Eq (4) from [mantid_rebin_errors.pdf](https://github.com/mantidproject/mantid/files/1702768/mantid_rebin_errors.pdf) only applies if `f_i` is a constant. In reality it should be a random variable with its own distribution function which defines the probability that a fraction `d_i` of the bin width contains fraction `f_i` of the signal in that bin. `Rebin2D` assumes that this distribution is a delta function \delta(f_i - d_i). This is only possible if all the events in the bin are evenly spread across its width. Which is not very realistic as I see it. Therefore, the true error should be greater than what Rebin2D outputs.

**Comment by mantid-roman** [comment]
I have written some formulas here [rebin2d_vs_rebin.pdf](https://github.com/mantidproject/mantid/files/1739600/rebin2d_vs_rebin.pdf) in support of my opinion.

**Comment by mducle** [comment]
@mantid-roman thanks for this. I think you're right, and after meeting with people in my group we're now happy with the `Rebin` description.

@SimonHeybrock @martyngigg So, I think we now need to change `Rebin2D`. There is this old PR: #20953 which can be resurrected. What do you think?

**Comment by martyngigg** [comment]
@mducle I'm happy for #20953 to be resurrected.
