### ISSUE TITLE
Indirect Data Analysis ConvFit tab crash, no documentation

### ISSUE THREAD

**Issue by josephframsay** [mantidproject/mantid#21906]
The documentation for the ConvFit tab ([here](https://www.mantidproject.org/Indirect:Indirect_Data_Analysis)) is no longer relevant to the GUI, and as a result it is not clear how to actually run a fit. If you load in the suggested workspaces from the ISIS sample data, the click Fit -> Fit, MantidPlot crashes with the following exception:
`Unexpected exception: Invalid value for property Workspace (Workspace) "irs26176_graphite002_conv_FixF_s0_Workspaces": Workspace "irs26176_graphite002_conv_FixF_s0_Workspaces" was not found in the Analysis Data Service
`

There is also no documentation (at least on this page) for the **I(Q, t)**, **I(Q, t) Fit** or **JumpFit** tabs

**Comment by brandonhewer** [comment]
@josephframsay It sounds as though you run the ConvFit tab without a Fit Function selected, although this is no longer clear from the Documentation, which is several years out of date. 
Of course, it shouldn't be possible to crash MANTID - it may be best to separate this issue into two parts -- one for documentation and one for this crashing error -- since the crashing problem also would appear to be the same problem outlined in #21905

**Comment by robertapplin** [comment]
This is no longer an issue (as of Mantid version 3.13)
