### ISSUE TITLE
FDA Home tab

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#21956]
A home tab for the FDA GUI (what is not included in the data loader)

**Comment by AnthonyLim23** [comment]
widget 1: 
[instrument.pdf](https://github.com/mantidproject/mantid/files/2327226/instrument.pdf)

widget 2:
[detector_grouping.pdf](https://github.com/mantidproject/mantid/files/2327267/detector_grouping.pdf)

widget 3 (we can reuse this in the grouping tab):
[plot.pdf](https://github.com/mantidproject/mantid/files/2327295/plot.pdf)

widget 4:
will be the Run information (see the current GUI). This should just receive info.


The headings are included for simplicity but should not be in the actual widget, but instead in the overall tab.

**Comment by TWJubb** [comment]
![hometab](https://user-images.githubusercontent.com/33163693/45371771-471bad80-b5e3-11e8-8213-6b191e0d2706.png)

**Comment by TWJubb** [comment]
First draft of the views is above, the home tab contains four widgets (in the view these are the four grey bordered boxes). There are additional edits and button which appear when selecting a pair, when selecting an option from the rebin combo box, and when changing the dead time combo box to "From Disk" rather than "From File"

**Comment by TWJubb** [comment]
![hometab2](https://user-images.githubusercontent.com/33163693/45499764-f8058200-b774-11e8-8fb0-b2bb28d256e7.png)

**Comment by TWJubb** [comment]
Neatened it up a bit and added the basic functionality to grab information from the loaded workspace and populate the interface.
