### ISSUE TITLE
LARMOR Reductions can be excessively slow.

### ISSUE THREAD

**Issue by Mantid-Matthew** [mantidproject/mantid#22897]
It was reported that LARMOR reductions were taking over a weekend to fully reduce. An example script is 
[MnSi_Pressure_February_2018.py.zip](https://github.com/mantidproject/mantid/files/2188718/MnSi_Pressure_February_2018.py.zip)

Preliminary investigations seem to point towards the slowdown occurring due to the number of event slice reductions being done. Currently the workflow for this is involves running the entire reduction for each event slice so that for example if you have n event slices, everything is done n times.

Profiling indicates that the time expensive operations of this reduction are
* masking
* moveing
* slicing
* convert to q
* convert to wavelength
* validating the state, in particular  lines 232->238 of mask.py take a lot of time when repeatedly checked.

Of these only convert to q needs to be done for every event slice the rest could be done once. The validation should also be changed so it does not check files exist as this will become clear when they fail to load anyway.

**Comment by TTitcombe** [comment]
After investigating reordering the workflow to perform everything except convert to q before event slicing, it was discovered that,  in pratise, only cropping can be performed before slicing. Because of the bugs in masking event workspaces (#23973), we must convert to histogram early. 
The foundation for splitting the workflow into pre-slice operations and post-slice has been implemented in branch `22897_reorder_event_slice_reductions`. If the event workspace bug has been fixed, then we can continue with this work
