### ISSUE TITLE
LoadLog skips logs

### ISSUE THREAD

**Issue by mantid-roman** [mantidproject/mantid#22963]
**Original reporter:** Freddie Akeroyd

### Expected behavior
LoadLog should load all logs from the log file.

### Actual behavior
Sometimes it skips some logs.

### Steps to reproduce the behavior
Load the same workspace from two files:
1. \\\\isis\inst$\ndxoffspec\instrument\data\cycle_17_1\OFFSPEC00042712.raw
2. \\\\isis\inst$\ndxoffspec\instrument\data\cycle_17_1\OFFSPEC00042712.nxs

The workspace loaded from the nexus file has more logs than that from the raw file.

### Platforms affected
All

**Comment by FreddieAkeroyd** [comment]
Hi Roman, I took a bit more of a look and it seems to be due to the fact they have a block called NSPECTRA and a log called this is already created by the raw loader. The current LoadLogs() implementation seems to exit when it gets an error rather than continuing with the rest of the blocks.  Moving the exception handling to inside the loops at the end of loadThreeColumnLogFile() seems to fix it.

**Comment by mantid-roman** [comment]
Thanks, Freddie.

**Comment by FreddieAkeroyd** [comment]
Shall i push a fix to a branch?

**Comment by mantid-roman** [comment]
Yes, please.

**Comment by FreddieAkeroyd** [comment]
Ok, I've pushed a fix. I know a release is happening shortly and we had a problem recently on OFFSPEC with some logs not making it into the NeXus file so I was keen this workaround option was working. Thanks.

**Comment by mantid-roman** [comment]
The branch should be based on `release-next` not `master`. I'll make a new branch and a new PR.

**Comment by FreddieAkeroyd** [comment]
Sorry, I didn't read down far enough to see release-next. I'm a bit out of practice at Mantid development! Did "rebase --onto" not work then?

**Comment by FreddieAkeroyd** [comment]
good idea - thanks
