### ISSUE TITLE
Expand code completion in workbench

### ISSUE THREAD

**Issue by peterfpeterson** [mantidproject/mantid#23628]
In [`execution.py`](https://github.com/mantidproject/mantid/blob/master/qt/python/mantidqt/widgets/codeeditor/execution.py#L171) the code completion from the default template (which include `import numpy as np`) does not autocomplete things from the module. For example, in a "new" editor tab, execute the script, then type at the bottom of the script `np.all` which will not suggest completions options.

A library that can be used as a backend for code completion: 
https://github.com/davidhalter/jedi

**Comment by NickDraper** [comment]
From another issue closed as a duplicate


The following script will give an intellisense list of operations in mantidplot, but not the workbench.

We should make them equal
```
ws = CreateSampleWorkspace()
ws.
```

**Comment by NickDraper** [comment]
Additional test case:

Expected behavior
def func((a,b)):
    pass
When run from code editor should exit cleanly

Actual behavior
Script appears to run but then crashes code editor tab with error:

Traceback (most recent call last):
  File "C:\MantidInstall\bin\mantidqt\widgets\codeeditor\interpreter.py", line 332, in _on_exec_success
    self.view.editor.updateCompletionAPI(self.model.generate_calltips())
  File "C:\MantidInstall\bin\mantidqt\widgets\codeeditor\execution.py", line 184, in generate_calltips
    calltips.append(name + get_function_spec(attr))
  File "C:\MantidInstall\bin\mantidqt\widgets\codeeditor\execution.py", line 80, in get_function_spec
    calltip = ','.join(args)
TypeError: sequence item 0: expected string, list found
Steps to reproduce the behavior
Enter

def func((a,b)):
    pass
into code editor and run

Platforms affected
I’m running in workbench 4.1.0 on Windows 10
