### ISSUE TITLE
Sliceviewer crashes with Matrix workspaces

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#26235]
### Actual behavior
The sliceviewer crashes the workbench when trying to open the sliceviewer on a "normal" matrix workspace.

It seems to start ok for MDWorkspaces. and it seems to be ok on linux.

### Steps to reproduce the behavior
1. open workbench
1. Load a worspace
1. right click and select sliceviewer
1. The window will appear white for a couple of seconds and then crash out to the error reporter.

The following file definately crashes, but it seems to be consistent for any matrix workspace.
SXD23767.raw (can be found in the training data)

### Platforms affected
Windows 8 and 10, and ubuntu.

**Comment by NickDraper** [comment]
@rosswhitfield Ross, I've asked Harry to look at this first as it seems to be only on windows, but if you could help at all it would be appreciated.

**Comment by hsautessella** [comment]
This does also appear to be a problem on the master build of my Ubuntu 18 VM. 

The line causing the issue seems to be: https://github.com/mantidproject/mantid/blob/6e380560c08100841365b1e1d93d0945683d22cd/qt/python/mantidqt/widgets/sliceviewer/samplingimage.py#L59 

I'll carry on looking into it, but just giving a heads up that it's also happening on Ubuntu 18

**Comment by martyngigg** [comment]
I assume this is to do with either numpy or matplotlib versions which is why probably I can't see it.
