### ISSUE TITLE
Remove or fix drag and drop tabs from Muon Analysis

### ISSUE THREAD

**Issue by Matthew-Andrew** [mantidproject/mantid#26613]
Currently the code to allow tabs in muon analysis to be dragged and dropped back into the main GUI is disabled as it does nothing on Linux and windows and leads to errors on OSX. This should either be fixed to work correctly or removed.

**Comment by AnthonyLim23** [comment]
@Mantid-Matthew is this done?

**Comment by Mantid-Matthew** [comment]
No this is an issue to properly resolve something that was quickly fixed previously.

**Comment by Mantid-Matthew** [comment]
This is related to #24678 as this issue comes back to the fact that the tabbing on the new Muon Analysis GUI is not well implemented. This leads to numerous usability issue particularly on OSX and I suspect if any of the instruments scientists used anything except windows it would be receiving substantially higher priority. We are currently using a handrolled tabbing implementation but would be much better served to use the QMainWindow QDockWidget implementation which comes with Qt and would resolve many of these issues.

**Comment by AnthonyLim23** [comment]
@DavidFair does the tabbing work ok on mac now (you need to double click to undock/redock)?

**Comment by sf1919** [comment]
This is now blocked by #33044

**Comment by ConorMFinn** [comment]
Popping out of tabs is now performed by double-clicking them. Dragging code removed via #33141 due to segfaults on macOS. Windows are movable above the main analysis GUI. Found a bug with the GUI re-attaching the windowed tabs but only on macOS, issue at #xxxxx
