### ISSUE TITLE
Use 1:1 mapping for det to spectra in KafkaStreamDecoders.

### ISSUE THREAD

**Issue by LamarMoore** [mantidproject/mantid#26692]
Currently the streamers expect to receive a stream for the detector to spectrum mapping which is a purely ISIS concept and will not be utilized by the ESS. This needs to be accounted for in the stream decoders.

**Comment by OwenArnold** [comment]
@LamarMoore can you provide any more detailed information around this issue please. I'd like to find someone to pick it up.

**Comment by OwenArnold** [comment]
@LamarMoore could you also describe what the current work arounds would look like, so that we know how painful this would be to work with at v20 in current state.

**Comment by matthew-d-jones** [comment]
We would need to send a detector-spectrum map via Kafka along with the run start message. We don't have a workaround in place, we would probably have to add some code to Nicos to serialise this extra message.

If I remember correctly from our previous conversations about this, generating a 1:1 map would be consistent with what happens when loading non-ISIS event data from file.
