### ISSUE TITLE
Cannot import exported batch script when sample geometry unticked

### ISSUE THREAD

**Issue by DavidFair** [mantidproject/mantid#26912]
**Original reporter:** ISIS/Sarah

### Expected behavior
Exporting a processing table from the GUI should be importable
### Actual behavior
The table cannot be imported as sample geometry is included when the columns are unticked
### Steps to reproduce the behavior
- Export table to batch file
- Check sample geometry was included
- Attempt to import
### Platforms affected
All

**Comment by gemmaguest** [comment]
Not sure if it's the same thing but Najet had a problem where the batch file seemed to load ok but when she tried to process the table the runs could not be found. When she deleted the additional columns and re-loaded, it would then process ok. She said it was a bug she'd seen a lot before and it's because there are an odd number of columns in the batch file.
