### ISSUE TITLE
Table workspace algorithm

### ISSUE THREAD

**Issue by Matthew-Andrew** [mantidproject/mantid#26928]
Currently the workspaces produced by the Muon Analysis 2 GUI have a corrupted history. This is due to them passing workspaces around privately without going via the ADS. The workflow should be updated so that workspaces produce a valid workspace history.

**Comment by Mantid-Matthew** [comment]
This has been partially resolved. Workspace history now works upto the end of the fitting step in the workflow. It does not currently work for the create results table step however. This is due to the fact that there is currently no algorithm to create a non empty TableWorspace so the results table creation cannot be captured by the history. A new algorithm to create a filled table needs to be created and then added to the GUI workflow to complete this issue.
