### ISSUE TITLE
'import nxs' broken on Windows installation

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#27018]
### Expected behavior
`import nxs` is successful

### Actual behavior

The import results in 

```
import nxs as nxs
 
OSError: File C:/Jenkins/workspace/release_clean-win7/external/src/ThirdParty/bin/libNeXus-0.dll from environment variable NEXUSLIB does exist
```

### Steps to reproduce the behavior
Start MantidPlot or Workbench and run `import nxs`

### Platforms affected
Windows with an installed package. A developer build is fine.

**Comment by DannyHindson** [comment]
Error was in release 4.1.0 also

Seems to be caused by a failed attempt to overwrite C:\MantidInstall\bin\mantid\kernel\packagesetup.py (which has a full path to the nexus dll) with packagesetup.install.py (which has a relative path) during the install

The overwrite is attempted using a call to mtd_install_files in the following file:

D:\MantidSource\mantid\Framework\PythonInterface\mantid\kernel\CMakeLists.txt

There are only 2 uses of the mtd_install_files function in the whole install so possibly a problem with the function. I think the file (INSTALL ) command it uses perhaps only overwrites files if the datetime stamp on the file being copied is newer than the one that's there already

Will try to debug by adding some "message(STATUS )" statements to the cmake files

**Comment by martyngigg** [comment]
@DannyHindson Ah yes I see what is happening now. I wonder if inside `mtd_install_files` we could `touch` the packagesetup.install.py before we try to "install" it to trick the function. We have to use `execute_process(${CMAKE_EXECUTABLE} -E touch` as `file(TOUCH` was added in more a recent version of cmake than we are using.
