### ISSUE TITLE
Instrument View window shrink

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#27244]
This issue is more serious than it seems, as after the shrink happens, peak picking does not work!

### Expected behaviour
Instrument Viewer should take up the whole plot window.
### Actual behaviour
If you switch to any view other than Full 3D (so cylindrical or spherical), the plot only takes up the bottom left quarter. This remains for full 3D if switched back to, but it will go to the full size if you resize the instrument viewer pop-up
### Steps to reproduce the behavior
Load any data and right click 'Show Instrument'
Change to cylindrical or Spherical
### Platforms affected
Only seen on Workbench (4.0 and 4.1) on Mac

<img width="1306" alt="Screenshot 2019-11-04 at 09 26 01" src="https://user-images.githubusercontent.com/55980573/68112000-4d0bd680-fee8-11e9-8a59-cd5ec3673070.png">

**Comment by DanielMurphy22** [comment]
This is not an issue on MantidPlot

**Comment by DanielMurphy22** [comment]
Interestingly when I connected a second screen to the Macbook, this issue was not longer a problem on the second screen, only on the main laptop screen!

**Comment by DanielMurphy22** [comment]
Also, a related issue about peak numbers appearing "Blurry" in workbench has been reported. The user reported this error message being output which may be relevant to either (or neither) of these issues: 
`Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.`

**Comment by sf1919** [comment]
I've been trying to follow the Basic Introductory training and in doing the Exercises for Instrument View (https://docs.mantidproject.org/nightly/tutorials/mantid_basic_course/connecting_data_to_instruments/06_exercises_c.html
) I'm having the same issue with the plot. I'm on Windows 10 rather than a Mac though. For ref this is the Nightly download of version 5.0 from 07/09/20.

The issue also means I'm unable to complete the exercise as the mini plot doesn't work and remains blank for all the detectors.

**Comment by AnthonyLim23** [comment]
@gemmaguest said its ok on Linux

**Comment by gemmaguest** [comment]
> 
> 
> @gemmaguest said its ok on Linux

With the caveat that I'm using X11 forwarding to display locally on my Windows machine... which has affected a few display-related things in the past....

**Comment by gemmaguest** [comment]
Fixed by #29432
