### ISSUE TITLE
Marker lines cannot be hidden

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#27290]
We would like to hide the marker lines in workbench plots. The user may just want the label.

**Comment by martyngigg** [comment]
This feels like a feature request. Is it really necessary for the release?

**Comment by NickDraper** [comment]
Pushing this out of the release as it is entering it's final week and we won't have time for this.

**Comment by NickDraper** [comment]
So I've looked into this ...

It turns out that matplotlib  does not support this, if you set the LineStyle to "None" or None, which should be acceptable, then Matplot lib gives you a Solid line instead.

Also the is_visible(bool) function does not do this.

Therefore I'm going to close this as not reasonably possible, I think using markers this way is abusing them to add text.
