### ISSUE TITLE
Numbers not shown on Colourfill Plot scale bar when change to Logarithmic

### ISSUE THREAD

**Issue by DannyHindson** [mantidproject/mantid#27379]
During the smoke testing I noticed that changing the scale to logarithmic on a colour fill plot causes the numbers to disappear on the colour scale (in Workbench). I observe this on the Windows nightly builds but not on IDAaaS. Haven't tried on other platforms.

The default Min. value on the dataset I'm using is zero. If you change the Min. value or Max. value to something different the numbers on the scale re-appear eg changing the Min.value to a small positive number rather than zero in the example below.

Not quite the same, but similar to https://github.com/mantidproject/mantid/issues/27151

Investigate using the symmetric log in MatPlotLib as slice viewer uses this and that seems to handle zero better

### Expected behavior

Load MAR11060
Create Colour Fill plot
Open up Figure Options
Go to Images tab and change Scale to Logarithmic
Colour scale bar should have numbers

### Actual behavior

Colour scale bar doesn't have numbers:

![image](https://user-images.githubusercontent.com/56295817/68846559-32deaf00-06c5-11ea-907a-71ecbef9e3e8.png)

### Steps to reproduce the behavior

See above

### Platforms affected

Windows, IDAaaS

**Comment by PhilColebrooke** [comment]
I've been doing some investigating into this issue for whoever ends up doing it (probably me). It would appear that the colorbar scale fails to appear if the min value is "too small", but the smallest value that it can be set to without the numbers disappearing depends on what the max value is.

Currently in the code, if the scale is set to logarithmic and the minimum value is zero, the minimum value is changed to 1e-6 to prevent an error caused by doing log0.

I've found that the numbers on the scale disappear if:
- min value = 1e-7 and max value = anything between 100 and 10,000
- min value = 1e-6 and max value = anything between 10,000 and 1,000,000.
- min value = 1e-5 and max value = anything between 10,000 and 1,000,000.
- min value = 1e-4 and max value = anything between 1,000,000 and 1e8.

The solution?
¯\_(ツ)_/¯
