### ISSUE TITLE
Rounding errors in first good data bin cropping

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#27384]
@Mantid-Matthew can you fill this out with an example?

**Comment by Mantid-Matthew** [comment]
For muon anlaysis only data after the first good data time should be considered for analysis. We currently pessimistically crop bins where if a bin has some good and some bad data so that only bins whose time falls completely after first good data are included. This leads to some odd behaviour when first good data is set to zero whereby sometimes the first bin is included and sometimes it is not. 

This is likely due to rounding errors when comparing to zero so could be fixed by doing a slightly less strict comparison but should be investigated in any case.
