### ISSUE TITLE
NaNs prevent Instrument View

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#27642]
**Original reporter:** [ISIS]/[James Lord] on [Mantid Fourm](https://forum.mantidproject.org/t/masking-detectors-from-a-script/79/3) (See the bottom of the post)

### Expected behavior
A workspace containing Nan or Infinity Values should be Masked and the workspace should load correctly into Instrument View
### Actual behavior
Doesn't load.
### Steps to reproduce the behavior
Create a workspace containing Nan values by dividing by a workspace with 0 values or setting values with a command like ws.dataY[0](0) = 'NaN' :
```
from mantid.simpleapi import *
ws = CreateSampleWorkspace()
for i in range(150):
    ws.dataY(i)[2] = 'NaN'
```
a current work-around is: 
```
ws_fix = ReplaceSpecialValues(ws,NaNValue = -111, Infinityvalue = -111)
MaskDetectorsIf(ws_fix, Value = -111)
```
but we're aiming for Instrument View to be intelligent enough to Load and Mask nan and inf values!
### Platforms affected
All

**Comment by peterfpeterson** [comment]
We just discovered this in mantidworkbench as well with "bad" values in masked pixels. Mantidplot caught the exception and popped a dialog box with a helpful error message and the supplied instructions.

The workspace we were using had the those pixels masked, and pointed out that the default range in the color scale, which should ignore masked detectors, does not. 

Additionally, it would be helpful if `MaskDetectorsIf` could mask nan/inf directly rather than the two step method mentioned above.
