### ISSUE TITLE
Fit MDHistoWorkspace Workbench

### ISSUE THREAD

**Issue by peterfpeterson** [mantidproject/mantid#27794]
**Original reporter**  Garrett Granroth at ORNL

In Workbench, it is possible to generate a plot from an MDHistoWorkspace from a script.
Subsequently, clicking `Fit` on this plot window produces an Error Reporter and the following:

```
File "/opt/mantidnightly/lib/workbench/plotting/figuremanager.py", 
line 331, in fit_toggle self.fit_browser.show() 
File "/opt/mantidnightly/lib/mantidqt/widgets/fitpropertybrowser/fitpropertybrowser.py", 
line 140, in show self._add_spectra(allowed_spectra) 
File "/opt/mantidnightly/lib/mantidqt/widgets/fitpropertybrowser/fitpropertybrowser.py", 
line 78, in _add_spectra self.addAllowedSpectra(name, spec_list) 
TypeError: index 0 has type 'NoneType' but 'int' is expected`
```
**Suggestions**
Plotting an MD workspace is not a so-called right-click option in Workbench yet, but if it were **either**: 
- The fitting tab should be disabled to disallow fitting an MD HistoWorkspace
- The fitting tab could be altered to support fitting (would probably have an internal conversion to a MatrixWorkspace

**Definitely** worth adding the ConverttoMatrixWorkspace (actually runs the `ConvertMDHistoToMatrixWorkspace` algorithm) option in the right-click menu for MDHistoWorkspaces, as this is how it works in Plot.

**Comment by granrothge** [comment]
The following is a script that shows the behavior.  
 - Run it from the workbench
 - When the plot pops up you will see the fit button
 - push it and it will generate the error
 - @peterfpeterson Pete feel free to put this data somewhere for others to access.

from __future__ import (absolute_import, division, print_function, unicode_literals)

# import mantid algorithms, numpy and matplotlib
import mantid.simpleapi as mtds

import matplotlib.pyplot as plt
from mantid import plots

import numpy as np
IPTSnum = 23714
rn_num = 126036
Datapath = '/SNS/ARCS/IPTS-{:d}/shared/autoreduce/'.format(IPTSnum)
flnm = 'ARCS_{:d}_autoreduced.nxspe'.format(rn_num)
mtds.LoadNXSPE(Filename=Datapath+flnm, OutputWorkspace='indat')
# ApplyDetailedBalance(InputWorkspace='indat',Temperature='973', OutputWorkspace='indat')
mtds.ConvertToMD(InputWorkspace='indat', QDimensions='|Q|', OutputWorkspace='sqemd')
# generate the cut direct to a workspace handle rather than a workspace name
cut1 = mtds.BinMD(InputWorkspace='sqemd', AlignedDim0='|Q|,1.8,2.8,1', AlignedDim1='DeltaE,-20,50,140')

# plot the cut
# first create the figure
f, ax = plt.subplots(subplot_kw={'projection': 'mantid'})
# plot as errorbar
ax.errorbar(cut1, fmt='bo')
# plot as plot
# ax.plot (cut1)

f.show()


# extracting an MD workspace to a masked numpy array
out = plots.helperfunctions.get_md_data(cut1, plots.helperfunctions.get_normalization(cut1))
