### ISSUE TITLE
Plot resets when moving start/end x markers in indirect data analysis

### ISSUE THREAD

**Issue by alicerussell1** [mantidproject/mantid#28104]
### Expected behavior
The changes should stay set

### Actual behavior
The plot goes back to the default zoom and scale

### Steps to reproduce the behavior
Open the indirect data analysis interface.
Go to one of the fitting tabs
Load a workspace
Right click on the plot and change the x axis scale to `log`
Move the marker
The plot resets

Zoom in on the plot
Move the markers
Plot resets 

### Platforms affected
Tested on window, bug is also in 4.2

**Comment by Harrietbrown** [comment]
This is related to a more broad issue related to the context menu not properly communicating with the gui. This isn't likly to be fixed in this release and I have descovered another issue that can cause a crash through manipulating the context menu, so I have made a PR to dissable the menu for now as Mathew says he has not seen it bieng used by the scientists.

**Comment by Harrietbrown** [comment]
After reenableing the context menu I cannot recreate the original issue. I think It is safe to put the context menu back.
