### ISSUE TITLE
No Tick Marks on Instrument View Colour Bar if Values too Close

### ISSUE THREAD

**Issue by ConorMFinn** [mantidproject/mantid#28142]
### Expected behaviour
The scale on the workbench instrument viewer should always have some tick marks on it when using Log10. 
### Actual behaviour
If the max and min values are too close together no tick marks appear on the colour bar. 
### Steps to reproduce the behaviour
1. Load MUSR62250
2. Switch the colour bar to SymmetricLog10
3. See no tick marks
### Platforms affected
All, Workbench Only

**Comment by DanielMurphy22** [comment]
I think this is just because the major tick marks (10^4, 10^5) are outside of the autoscaled range for the colorbar (for this data set). If you change the max and min to 10e4 and 10e5 then you see the tick marks! If we put minor tick marks on colorbars these would be visible for this range but we likely wouldn't have tick labels on minor tick marks. I agree it looks bad having no tick marks at all in certain circumstances.
