### ISSUE TITLE
Hide confusing intermediate indirect workspaces. 

### ISSUE THREAD

**Issue by Matthew-Andrew** [mantidproject/mantid#28666]
Currently the Indirect FQ fit tab creates a HWHM workspace whenever data is loaded to used for fitting. This creates confusion on the user end and means that the workflows are more difficult to replicate in scripts. This functionality should therefore be moved into the fitting algorithms.

**Comment by Mantid-Matthew** [comment]
@Harrietbrown This issue is related to the F(Q) fitting issues you have been working on so re-assigning to you. Let me know if more info is needed.

**Comment by Harrietbrown** [comment]
not stale

**Comment by Harrietbrown** [comment]
Not stale

**Comment by Harrietbrown** [comment]
Not stale

**Comment by Harrietbrown** [comment]
Not Stale

**Comment by Harrietbrown** [comment]
Not stale

**Comment by Harrietbrown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Hide _HWHM workspaces produced by FqFit https://github.com/mantidproject/mantid/issues/28666](https://trello.com/c/gSMuBoG2/9-hide-hwhm-workspaces-produced-by-fqfit-https-githubcom-mantidproject-mantid-issues-28666)

**Comment by AnthonyLim23** [comment]
making it a hidden workspace will break the workspace history. It would probably be better to delete the ws at the end of the processing step.

**Comment by Harrietbrown** [comment]
For this we can move the creation of the HWHM into when the run button is clicked and deleate at the end, but we will still need a a workspace that can be plotted.

**Comment by AnthonyLim23** [comment]
not stale

**Comment by robertapplin** [comment]
Still one last part of this needs to be completed

**Comment by robertapplin** [comment]
I've considered a couple of potential solutions for this issue, with the first option being the preferred approach, while the second one, although functional, is not an ideal fix.

**Solution 1:**
To address the concern of the HWHM workspace being output into the ADS, the proposal is to store it solely in memory. However, implementing this solution requires a substantial effort to decouple the Data Analysis interface code from the ADS. The advantages include:

- Independence from the ADS singleton, leading to more better designed code and theoretically reducing bugs.
- Ensuring the "Script to Clipboard" feature for result workspaces will reliably work.

On the downside:

- Significant effort is needed to disentangle the Data Analysis interface from the ADS.
- The QENSFitSequential and QENSFitSimultaneous "Input" property would require re-work for this approach.
- Users will lose the ability to view intermediate workspaces during their workflow for verification.

**Solution 2:**
This alternative involves using a hidden workspace for the HWHM workspace in the ADS by prefixing "__" to its name. While it achieves the goal of concealing the HWHM workspace and is a quick implementation, it comes with drawbacks:

- The "Script to Clipboard" feature will still not work.
- It's a quick fix that sidesteps the underlying issue of the interface being heavily entangled with the ADS.

**Conclusion:**
From this investigation it is apparent that Solution 2 is not a great solution and feels like a "quick fix". Also, Solution 1 demands a considerable amount of time and effort. Given that this issue is of low priority for Indirect Inelastic, I do not think a solution for this issue should be explored any further. Now I have a clearer understanding of the trade-offs and priorities regarding this issue, I am going to close it. If circumstances change or the issue becomes more critical in the future, it can always be revisited.
