### ISSUE TITLE
Colorfill plots setting z-axis scale and limits

### ISSUE THREAD

**Issue by darominski** [mantidproject/mantid#28801]
### Expected behavior

One should be able to select z-axis and change limits and scale from the `Figure Options` pop-up of a Colorfill plot when `Workspace2D` is plotted.

### Actual behavior

It is not possible to select the z-axis, and thus change limits nor scale from the Figure Options pop-up. 

### Steps to reproduce the behavior

In Mantid Workbench:
Load a `Workspace2D`, e.g. 164198.nxs from TrainingCourseData 
Right click on the workspace, select `Plot` and then `Colorfill`.
A pop-up with the plot should appear. 
Select `Figure Options`, try to select the z-axis.

### Platforms affected
Checked on Ubuntu 18.04 but I presume other platforms are also affected.

**Comment by DanielMurphy22** [comment]
I believe the current behaviour is intentional. [The Z axis option in the Figure Options was added for 3D surface and wireframe plots](https://github.com/mantidproject/mantid/pull/28473). As such, the Z axis was disabled for 1D line plots and 2D Colorfill plots.
On a colorfill plot, the "Z-axis" is currently referred to as the Colorbar or Image. So in Figure Options, under the [Images tab](https://docs.mantidproject.org/nightly/tutorials/mantid_basic_course/loading_and_displaying_data/06_formatting_plots.html#image-plots) the scale and limits can be changed. These can also be changed from the [right-click menu](https://docs.mantidproject.org/nightly/tutorials/mantid_basic_course/loading_and_displaying_data/06_formatting_plots.html#click-menus) on the plot > Colorbar (Lin/Log), or [Double-click ](https://docs.mantidproject.org/nightly/tutorials/mantid_basic_course/loading_and_displaying_data/06_formatting_plots.html#click-menus)on the Colorbar Axis (Min/Max/Lin/Log).

**Comment by gvardany** [comment]
@DanielMurphy22 This is exactly what is not working. In the image tab we don't get the workspace in the combo box, but for some reason we see the individual spectra.

**Comment by gvardany** [comment]
![Screenshot 2020-06-10 at 11 18 58](https://user-images.githubusercontent.com/16865759/84250432-56a78d80-ab0c-11ea-815e-2a2a3f9322a1.png)
![Screenshot 2020-06-10 at 11 19 18](https://user-images.githubusercontent.com/16865759/84250444-59a27e00-ab0c-11ea-869c-bf1932ec81c8.png)

**Comment by alicerussell1** [comment]
@gvardany I can't seem to replicate this. What workspace have you used here?

**Comment by gvardany** [comment]
This was the file, just rename to .nxs and load.
[d16_colorfill.nxs.zip](https://github.com/mantidproject/mantid/files/4882541/d16_colorfill.nxs.zip)

**Comment by alicerussell1** [comment]
Ah okay I can see the issue now, I'll look into this
