### ISSUE TITLE
Sliceviewer cursor data axes mismatch after swapping x/y

### ISSUE THREAD

**Issue by clayton-tom** [mantidproject/mantid#30307]
### Expected behavior
Switching axes should cause the data shown under x/y in the cursor view to swap correctly

### Actual behavior
Found with 4d data, may be present with 3d: switching the axes on some 4d data causes the x/y data for the cursor position to get mismatched. In the first screenshot, the cursor data seem correct, but on the second (having switched the x and y axes) the y value is negative and x positive, rather than vice versa which the axes scales would indicate
![image (5)](https://user-images.githubusercontent.com/68227228/104178726-bba8c600-5402-11eb-9ab1-216c3d37854a.png)
![image (6)](https://user-images.githubusercontent.com/68227228/104178748-c19ea700-5402-11eb-96a4-5cb369136c01.png)

### Platforms affected
Found on windows, assumed on all

**Comment by Pasarus** [comment]
This I believe was indicative of an issue with slice viewer not updating the plot correctly, on switching/swapping axes. With a call to self.update_plot later on it should update the actual plot data. The issue with the cursor data being wrong is because of the underlying data not being update properly.
