### ISSUE TITLE
Error reporter should check for a valid email address

### ISSUE THREAD

**Issue by clayton-tom** [mantidproject/mantid#31292]
The error reporter optionally allows a user to enter an email to identify themselves, this should be checked with a regex to ensure it is valid if one is entered.

**Comment by martyngigg** [comment]
We need to be careful here in that this might seem simple at first glance but is more [complex than it seems](https://www.regular-expressions.info/email.html). I think we'd want to offer that it might not look right but still allow it.

I'm also going to remove the 6.2 milestone as I'd prefer it if new items remain unassigned to a milestone so that it's clear they are not yet scheduled to be worked on.
