### ISSUE TITLE
Clicking "Fit" in plot on workspace with 1 bin raises an unhandled exception

### ISSUE THREAD

**Issue by dtasev** [mantidproject/mantid#31363]
**Original reporter:** Dimitar ISIS

### Expected behavior
I am not sure whether fitting a workspace with 1 bin makes any sense, but it shouldn't be an unhandled exception. Perhaps a message box/warning would be more suitable.

Could be a good induction issue!

### Actual behavior
An unhandled exception is thrown which opens the error reporter. This is the traceback:
```
Traceback (most recent call last):
  File "C:\MantidInstall\bin\workbench\plotting\figuremanager.py", line 370, in fit_toggle
    self.fit_browser.show()
  File "C:\MantidInstall\bin\mantidqt\widgets\fitpropertybrowser\fitpropertybrowser.py", line 151, in show
    self._add_spectra(allowed_spectra)
  File "C:\MantidInstall\bin\mantidqt\widgets\fitpropertybrowser\fitpropertybrowser.py", line 72, in _add_spectra
    self.addAllowedSpectra(name, spec_list)
Exception: unknown
```

### Steps to reproduce the behavior
- Create a 1-bin workspace:
```
CreateWorkspace(OutputWorkspace='test_ws', DataX='1,2,3,4,5', DataY='1,2,3,4,5', NSpec=5)
```

- Double click it, then click the `Fit` button

### Platforms affected
Found on Windows, but likely all.

**Comment by MialLewis** [comment]
As a note, the full traceback is as followed (file names in hashes):
#figuremanager.py# fit_browser.show() ->
#fitpropertybrowser.py#._add_spectra(allowed_spectra) ->
#fitpropertybrowser.py#.addAllowedSpectra(name, spec_list) ->
#fitpropertybrowser.cpp# addAllowedSpectra(const QString &wsName, const QList<int> &wsSpectra) ->
#MatrixWorkspace.cpp# getIndexFromSpectrumNumber(i) -> 
ERROR, SPECTRUM NUMBER NOT FOUND.

The error is due to the fact that the "getIndexFromSpectrumNumber" function is trying to find a spectrum index number usingr using a bin number rather than a spectrum number.

This issue occurs trying to fit a "bin plot", regardless of the number of spectra or number of bins on that plot. For example, the following plot (3 bins, ~350 spectra) still gives the error: 
![image](https://user-images.githubusercontent.com/95620982/146773881-6c93aed8-be29-4baf-aaec-ba04e285a043.png)

Is there a use case for ever fitting to a bin plot, or should the fit button just be removed/disabled on bin plots?
