### ISSUE TITLE
ICP_alarm files for INES prevent loading logs

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#31605]
### Expected behavior
Loading a raw file loads the logs successfully.
### Actual behavior
Loading INES raw data from a recent cycle gives the following error 
```
Unable to successfully run LoadLog Child Algorithm:
File/archive/NDXINES/Instrument/data/cycle_20_3/INS17770_ICPalarm.txt is not a standard ISIS log file.
Expected to be a file starting with DateTime String format.
```
### Steps to reproduce the behavior
- Run Load on /archive/NDXINES/Instrument/data/cycle_20_3/INS17770.raw
- Mantid also tries to pick up the ICPalarm.txt file and then cannot load the logs fully.
- In the case of run INS17770, the ICP_alarm file is empty
### Platforms affected
All

**Comment by SpencerHowells** [comment]
@DanielMurphy22 It looks as if it is the same problem that we had with old IRIS data. This has files that are not standard. We now just give a warning message & ignore the error messages. The data is loaded ok. In order to find out about the missing data we had to delve into the old data acquisition programs & were unsuccessful in working out how to interpret the data. Fortunately that data is not required.

**Comment by thomashampson** [comment]
For some reason this is not happening on Windows.
