### ISSUE TITLE
Error in FDA when changing parameter value

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#32454]
**Original reporter:** James Lord

**Describe the bug**
An error occurs after changing a parameter in the fitting tab of FDA when the sequential tab is being filtered.

**To Reproduce**
1. Frequency Domain Analysis interface
2. Load HIFI 77767-68
3. On Transform tab, click `Calculate FFT`
4. On Fitting tab, add a Gaussian function
4. On Sequential tab, change the `Filter By` option to show only Real data.
5. On fitting tab, change the `PeakCentre` parameter of the modulus data to a different value
6. You get this error
![image](https://user-images.githubusercontent.com/40830825/132709875-5865d2ab-ed5d-4fdc-bf17-5ed103074bc4.png)

**Platform/Version (please complete the following information):**
All I assume

**Comment by AnthonyLim23** [comment]
Looking at the instructions, this happens because the modulus is not in the filtered list. We should either:

a. Change the options in the selector on the fitting tab to match the filtered results
b. When the selector is changed to something that is not in the filter, turn the filter off

The filter was added in this PR:
https://github.com/mantidproject/mantid/pull/32173/files

**Comment by martyngigg** [comment]
Fixed by #32468
