### ISSUE TITLE
tables in groups tab of muon nalysis are too small

### ISSUE THREAD

**Issue by Harrietbrown** [mantidproject/mantid#32987]
In muon analysis the boxes for the tables are too small, users can only see one at a time in regular resolution

**Original reporter:** Aidrian Hillier

**Comment by sf1919** [comment]
Further information - AH is most concerned about the first box on the tab showing more than 1 line as often not using the other boxes.

**Comment by AnthonyLim23** [comment]
can we have a screenshot please?

**Comment by sf1919** [comment]
![grouping_tab](https://user-images.githubusercontent.com/55837273/142017141-7f5a4200-5683-420d-ba1a-02cfca8075dc.png)

**Comment by AnthonyLim23** [comment]
I thought this might happen when we added the difference table and we did warn them. Without increasing the minimum height or removing stuff it is going to be difficult. 

The only potential thing I can see is the group range being on one line instead of 2. However, I think the other 2 tables will still be a single row.
