### ISSUE TITLE
ISIS SANS UI Niggles found in testing

### ISSUE THREAD

**Issue by DavidFair** [mantidproject/mantid#33284]
- [x] Add .TOML and .toml for both cases on case sensitive platforms so users don't have to use `*`
- [ ] CSV parsing error: `row n seems to be missing` shows (n-1)
- [ ] Load User File, loading *.txt resets file extension filter to a wildcard (RHEL only?)

Found in #33195

**Comment by smk78** [comment]
>Add .TOML and .toml for both cases on case sensitive platforms so users don't have to use *

The same applies to .TXT and .txt, of course!

**This is a particular annoyance for IDAaaS users and so it would be good to get this bug fixed sooner rather than later.**

Our preferred resolution would be to have the 
![image](https://user-images.githubusercontent.com/10938679/161027648-717330bb-c380-43ab-8a7b-1999a6b2192c.png)

selector allow the individual options

TOML files
toml files
TXT files
txt files
