### ISSUE TITLE
Ubuntu Workspace/Algorithm Smoke Tests   :man_astronaut: :woman_astronaut: :space_invader:

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#34541]
* Follow the instructions [here](https://download.mantidproject.org/ubuntu.html) to install the .deb for Ubuntu

**Before testing**:
- Check this testing issue relates to the OS you will test on.
- If unassigned, please assign yourself as for a normal Github issue.
- Please run these tests on the release package of Mantid; **not a locally built version**.

**Afterwards**:
- Comment below with any issues you came across.
- If no major issues were found, please **close this testing issue**.
- Check the main issue for this OS for other unassigned smoke tests.

If you have any questions please contact the creator of this issue.

 :man_astronaut: :woman_astronaut: :space_invader:

* Load some workspaces, try 5 from different instruments
* Show detectors on these workspaces
* Check Instrument Viewer for these workspaces, follow  documentation for  [Instrument Viewer Widget](https://docs.mantidproject.org/workbench/instrumentviewer.html) and some more detail on the picking tools in the [Basic Course](https://docs.mantidproject.org/tutorials/mantid_basic_course/connecting_data_to_instruments/03_investigating_data.html)
  - [x] Render tab 
  - [x] Draw tab 
  - [x] Pick tab 
  - [x] Instrument tree tab 
* Test 5 - 10 random algorithms, follow [how to run Algorithms](http://docs.mantidproject.org/nightly/tutorials/mantid_basic_course/algorithms_workspaces_and_histories/02_algorithms.html#algorithms) and [pick your favourite](https://docs.mantidproject.org/algorithms/)
 - [x] Help button 
 - [x] Validation of inputs 
 - [x] Overwriting workspace 
 - [x] Run the algorithm 
- [x] Check right-click options of the workspaces, they are listed [in the documentation](https://www.mantidproject.org/MantidPlot:_The_Workspace_Menu#Save_Nexus).

**Comment by darominski** [comment]
Issues found:
- Instrument Viewer, masking: When attempted with data from ILL instruments D11B, D22B from the UnitTest storage, any masking shape applied to data results in a popup with the following error: `An error occured when applying the mask to bins`, and the selected mask is not applied. However, mask is applied correctly when applied via select tube/bank tool. 
- Masking: possible issue (or a feature?): selecting a small portion of a long pixel and applying mask does not apply the mask to that pixel. Mask is applied only when it covers more than 50% of the pixel.
- Opening non-existing instrument: this doesn't seem to be a new issue, since the related data is from 2016, but when one attempts to open instrument for DEVA01360, a result is a hard crash. There is no instrument definition for that instrument, and Mantid shows an error in the message log when this data is loaded. Preferably, this would be caught and an informative dialog displayed.

No issues with algorithms. Masking the instruments that were causing issues for in the Instrument Viewer widget was not reproduced when explicit algorithm for masking was used.

**Comment by DanielMurphy22** [comment]
Thanks for reporting the above. Presumably the Draw tab masking issue / feature is the same for the last release? Can you check that quickly please?

**Comment by darominski** [comment]
I am going to have a quick look. In the meantime, while checking the second point about draw tab masking I found on a number of instruments that if one selects the entire instrument by a shape and tries to mask, then Mantid crashes. Looking into that as well.

**Comment by darominski** [comment]
Both are present since at least v6.3. The 'issue' with covering at least 50% of surface relates to the check whether the masked shape contains detector's centre, so probably an intended choice rather than an issue. I am going to cross that one out. The crash when masking the entire instrument in one go is troubling though, also because its behaviour is erratic and I can reproduce it consistently only on a number of instruments now. I would say this shouldn't stop the release but I will keep looking into this today.

**Comment by DanielMurphy22** [comment]
Thanks for all this! Can we close this testing task now if nothing is for this release?
