### ISSUE TITLE
Improve temperature handling in ABINS

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#34757]
investigate

**Comment by ajjackson** [comment]
Abins implements the (exponentially decaying) Debye-Waller temperature effect but not the (polynomially-increasing) Bose occupation effects. This leads to excessive damping at high Q.

The implementation of the Debye-Waller term also seems to be non-standard. It is described accurately in the [concepts docs](https://docs.mantidproject.org/nightly/concepts/DynamicalStructureFactorFromAbInitio.html) and the [academic paper](https://doi.org/10.1016/j.physb.2018.02.034) but seems unorthodox in the way that:
- the coth function is squared
- it is evaluated at the energy of each spectral point rather than at the point of summing modes to form *A*
The squared coth factor (i.e. <2n + 1> phonon occupation) may have been inspired by Eq (A2.84) of Mitchell et al "Vibrational Spectroscopy with Neutrons".

I am working to implement a more conventional Bose factor and Debye-Waller scheme, but have been struggling to reproduce the behaviour of competing codes. Likely this is due to the way the current method is "baked in" to Abins and some refactoring will be necessary in the improved implementation. Nonetheless the work is primarily guided by academic references including the Squires and Lovesy books and [Tomkinson, Warner & Taylor (1984)](https://doi.org/10.1080/00268978400100261).
