### ISSUE TITLE
Adding a new batch tab wipes the existing batch

### ISSUE THREAD

**Issue by gemmaguest** [mantidproject/mantid#34845]
**Original reporter:** Becky at ISIS

In the ISIS Reflectometry interface, if you go to Batch menu and select New, it will add a new batch tab. There is a bug where this incorrectly clears the experiment settings on any other batch tabs.

The bug happens with all instruments except INTER.

Steps to reproduce:
- Open the ISIS Reflectometry interface
- Set instrument to POLREF
- On the Experiment settings tab, change some values or enter a value in the table, e.g. `1` in ROI.
- Go to the Batch menu and select New
- The values you changed are reverted

**Comment by rbauststfc** [comment]
I think this is happening because within `MainWindowPresenter::initNewBatch` (which gets called as part of adding a new batch) we make a call to `BatchPresenter::initInstrumentList` to populate the instrument dropdown on the Runs tab. Doing this triggers `QtRunsView::onInstrumentChanged`, which ultimately loops through all batch presenters to notify them of the change, if the selected instrument has changed.

Initialising the instrument list sets INTER to be selected by default. When we're adding a new batch for INTER, therefore, there is no change in selected instrument and so experiment and instrument tab settings are not overwritten. However, when we add a new batch for any other instrument, we do register a change in selected instrument and this causes all batch experiment and instrument settings tabs to be reset. It's only after this call to initialise the instrument list that we then make a direct call to `BatchPresenter::notifyInstrumentChanged` to set the instrument to the one we actually want.

A potential solution might be to pass an instrument name in to `BatchPresenter::initInstrumentList` to avoid incorrectly triggering a change in instrument.
