### ISSUE TITLE
Polarization correction not applied to live data

### ISSUE THREAD

**Issue by gemmaguest** [mantidproject/mantid#34904]
Report to: Becky at ISIS

When running live data for POLREF with polarization analysis enabled, the correction does not appear to be applied. Running the same reduction on the TOF_live workspace by entering it into the runs table applies the correction ok, so it seems to be something to do with the way settings are passed through via the live data monitor.

**Comment by rbauststfc** [comment]
When we run live data we call `StartLiveData` and pass `ReflectometryReductionOneLiveData` as the post-processing algorithm to actually perform the reduction. The problem is that the `InputWorkspace` property on `ReflectometryReductionOneLiveData` is a `MatrixWorkspace` type, which means that when it's called with a `WorkspaceGroup` it automatically loops through the group and is called for each child workspace individually. Polarisation corrections are applied in the `processGroups` method of `ReflectometryReductionOneAuto`, and we can't reach this if the algorithms are being called separately on each child workspace.

Changing the `InputWorkspace` property type in `ReflectometryReductionOneLiveData` to a string will allow the corrections to be applied, but we need to make some changes to the method `_setup_slits` as this calls `SetInstrumentParameter`, which seems to be throwing an error following this change.
