### ISSUE TITLE
Add manual testing documentation for the ISIS Reflectometry GUI preview tab

### ISSUE THREAD

**Issue by rbauststfc** [mantidproject/mantid#34967]
We used the testing instructions [here](https://github.com/mantidproject/mantid/issues/31069) for manually testing the preview tab for the 6.6 release, but we need to update these and add them to the online manual testing documentation.

During [testing for the 6.6 release](https://github.com/mantidproject/mantid/issues/34952) we felt that the `INTER45455_inst` test data made it difficult to tell if moving the ROIs on the spectrum viewer was updating the plot (the reduction was clearly being re-run, but we concluded that the data changes must be so small that you couldn't see the plot changing). If possible, it would be good to find some test data that made this clear.

**Comment by rbauststfc** [comment]
@gemmaguest I've written up some instructions for this but, before I put them into PR, I was wondering how best to make the `INTER45455_inst` test data available? It looks like the rest of the Reflectometry GUI testing data is either in the archive or in the ISIS sample data download. Would it be worth adding `INTER45455_inst` to the sample data and, if so, are there instructions anywhere for doing this?

**Comment by gemmaguest** [comment]
We're in a slightly awkward situation at the moment because this run is on the archive but by default it will load with the incorrect IDF - so really it is the IDF that is missing rather than the data. So we could just provide the IDF - but to test the GUI it is useful to have it already loaded on the run so we can just enter the name/run, because part of the test is that it will load it - hence we've been using that custom version of the data with the correct IDF loaded on it.

Because this is fake data I think I'd prefer to keep it out of the sample data. I think it is in the unit test data, so for now we could just get developers to load it from there. I think it is named `INTER45455` so we need to be explicit because it could easily be confused with the one on the archive.

This isn't ideal, but longer term this problem will go away because when they have the real 2D detector the default IDF will be correct so we can start using real data.

**Comment by rbauststfc** [comment]
Thanks @gemmaguest. I was just trying to play around with loading `INTER45455` from the unit test data, but the only way I could seem to do it was to load the hash file into the ADS. Is there another way this can be done that I'm missing?
