### ISSUE TITLE
AZERTY keyboard shortcut comment/uncomment does not work

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#35034]
**Original reporter:** @gui-co 
https://github.com/mantidproject/mantid/issues/34945#issuecomment-1385255013 

**Describe the bug**
On an AZERTY keyboard, the shortcut to comment/uncomment in the script editor (Ctrl+/) is not working

**Platform/Version (please complete the following information):**
 - OS: Ubuntu 18.04
 - Mantid Version 6.6 manual testing nightly 15th Jan but probably existed for a few releases.

**Comment by gui-co** [comment]
The shortcut is defined [here](https://github.com/mantidproject/mantid/blob/d910608db179dfd109a531ca65156ba0d01e3615/qt/python/mantidqt/mantidqt/widgets/codeeditor/tab_widget/codeeditor_tab_view.py#L137) using [this function](https://github.com/mantidproject/mantid/blob/d910608db179dfd109a531ca65156ba0d01e3615/qt/python/mantidqt/mantidqt/utils/qt/__init__.py#L123)

The problem is explained in [this Qt doc](https://doc.qt.io/qt-6/qkeysequence.html#keyboard-layout-issues). Briefly, the `Ctrl+/` shortcut requires a additional key (`Shift`) on an AZERTY keyboard and therefore becomes `Ctrl+Shift+:`.
