### ISSUE TITLE
Update ISIS SANS Manual Testing instructions to clarify about missing tooltips for Wavelength section

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#35085]
Found in manual testing: https://github.com/mantidproject/mantid/issues/34953#issuecomment-1387282634

**Describe the bug**
In the settings tab->q, wavelength, detector limits table->wavelength section there are missing tooltips. 

**To Reproduce**
Open the ISIS SANS GUI and navigate to the Settings tab->q, wavelength, detector limits table->wavelength section
hover the cursor over the input boxes in this section and there are no tooltips. 

**Expected behavior**
Basically all of the rest of the SANS interface has tooltips so it would be good to be complete! If these aren't worth adding then the Manual testing instructions should note down that this is the case.

**See comment https://github.com/mantidproject/mantid/issues/35085#issuecomment-2102716895 - we have decided to update the manual testing documentation to avoid confusion in future rather than add the tooltips.**

**Screenshots**
![image](https://user-images.githubusercontent.com/44416400/213218827-a1dfccc0-c861-4041-9e56-d283c84e93be.png)

**Platform/Version (please complete the following information):**
 - OS: All, found on Windows 10
 - Mantid Version 6.6 nightly manual tested 15th Jan but present on 6.5 release.

**Comment by rbauststfc** [comment]
@cailafinn, I've just spotted this from the last round of manual testing. We've never heard anything from the users about needing these tooltips, so as this is causing confusion I would suggest that we just update the manual testing documentation to make it clear that it's intentional that they're not there. If the users ever ask for them then we can obviously open an issue and add them in the future. I'm going to close this issue - are you happy to open an issue for updating the SANS manual testing docs?
