### ISSUE TITLE
Better Conda Installation instructions

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#36149]
**Description**
We have been sent the following feedback from an Instrument Scientist:
```
The instructions on the mantid installation page are quite vague with respect to conda.
I recently tried to install using anaconda on a windows system and found that the installed python version was not compatible.
 
Is there any further documentation provided that would help to understand when it is appropriate to use conda and what you have to have installed?
```

I agree, we could do with having better instructions for installing Mantid using conda. These instructions should say:
- Create an empty conda environment
- For Mantid >6.7 use python 3.10 `conda create --name myenv python=3.10`
- For Mantid <=6.7 use python 3.8 `conda create --name myenv python=3.8`
- Activate the environment
- Then run the conda install command
- The instructions should also give clear instructions how to open Mantid

**Comment by MialLewis** [comment]
Agree, instructions assume prior `conda` knowledge which is not guaranteed for our user base.

Can use `conda create -n myenv -c mantid mantidworkbench` so that the user doesn't have to worry about python versions.

Given our large number of dependencies, this takes an age to resolve, so it may be worth providing a direct link to a mamba install, enabling:

`mamba create -n myenv -c mantid mantidworkbench`.
