### ISSUE TITLE
Add algorithm aliases to the mantidplot gui

### ISSUE THREAD

**Issue by peterfpeterson** [mantidproject/mantid#8120]
This issue was originally [TRAC 7274](http://trac.mantidproject.org/mantid/ticket/7274)

Currently they are only accessible from python. They should appear in the autocomplete list for algorithms and in the algorithm tree.

**Comment by NickDraper** [comment]
This is somewhat complicated by the use of some algorithms (Load for example) using an alias to allow calls using the wrong case (load).  You would not want this case appearing.

I can see that we might want these in the search box, but I'm not sure about the tree.
 - for searching someone has a keyword in mind and we want to get the most usefull matches, so aliases should be included.
 - For the tree people are browsing, for example, what "diffraction algorithms are there that perhaps do xxx?", in this case we would want them to pick the correctly named algorithm and not the alias.  Also I think that because the alias will always be in the same categories it would be confusing to have two entries for the same thing.
