### ISSUE TITLE
ConvertToMD over subdivides

### ISSUE THREAD

**Issue by peterfpeterson** [mantidproject/mantid#8324]
This issue was originally [TRAC 7479](http://trac.mantidproject.org/mantid/ticket/7479)

When using ConvertToMD with single crystal data using the "SCD Event Data Reduction" interface with MAND_306_event.nxs, Max |Q| set to 5, and Apply Lorentz Correction turned on, the data (as viewed in the slice viewer) is over sub-divided. This can be seen by finding peaks and looking at one in the slice view. There will be boxes with zero counts next to ones with thousands of counts.

The suggested fix is that if a subdivision results in boxes with zero counts (when the source box has more than enough counts), don't do the subdivision.

**Comment by AndreiSavici** [comment]
I don't think this issue should be fixed. It is the desired behavior. Suppose I start with a large enough workspace, so all the MDEvents are in one side of it. Since by subdividing it would result in empty boxes, not proceeding with redistributing will stop the benefits of the adaptive box structure. If One does not like the binning, one can just rebin the data
